// ============================================================
// E-com.casa — Curated demo catalogue:
//   GARDEN (15) + OUTDOOR (12) + PLANTERS (10) + OUTDOOR PRIVACY (8)
// 100% original E-com.casa copy and merchandising data.
// ============================================================

import type { Archetype } from './types';

export const GARDEN: Archetype[] = [
  {
    key: 'fire-pit-bowl',
    name: 'Steel Fire Pit Bowl',
    subtitle: 'Corten-look steel · Ø 60 cm',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden', 'patio'],
    styles: ['rustic-modern', 'natural'],
    collections: ['garden-glow', 'outdoor-living'],
    priceCents: 11990,
    materials: ['Steel'],
    colour: 'Brown',
    dimensions: 'Ø 60 × 25 cm',
    weight: '9.5 kg',
    care: 'Brush out ashes when cold; a cover prolongs the finish.',
    shippingClass: 'HEAVY',
    imageKey: 'fire-pit',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    copy: {
      intro: 'A generous steel fire bowl that gathers the whole terrace around one warm centre.',
      benefits: ['Wide rim doubles as a footrest perch', 'Rust-toned finish weathers beautifully outdoors', 'Deep bowl holds a full evening of embers'],
      use: 'Terraces, lawns and courtyard evenings.',
    },
    matchKeywords: ['fire pit', 'fire bowl', 'garden fire'],
  },
  {
    key: 'wind-chime-brass',
    name: 'Brass Wind Chime',
    subtitle: 'Five tubes · deep tone · H 65 cm',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden', 'balcony'],
    styles: ['organic', 'mediterranean'],
    collections: ['natural-objects', 'garden-glow'],
    priceCents: 2990,
    materials: ['Metal'],
    colour: 'Brass',
    dimensions: 'H 65 cm',
    weight: '0.7 kg',
    care: 'Wipe occasionally; brass develops a soft patina outdoors.',
    shippingClass: 'SMALL',
    imageKey: 'garden-torch',
    copy: {
      intro: 'Five brass tubes tuned to a low, easy tone — the sound of the garden breathing.',
      benefits: ['Long, deep chime rather than a clatter', 'Solid brass weathers to a warm patina', 'S-hook hangs from branches and beams'],
      use: 'Pergola beams, balcony brackets and tree branches.',
    },
    matchKeywords: ['wind chime', 'brass chime'],
  },
  {
    key: 'bird-feeder-station',
    name: 'Garden Bird Feeder Station',
    subtitle: 'Steel pole + 3 feeders',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden'],
    styles: ['natural', 'rustic-modern'],
    collections: ['green-living', 'weekend-refresh'],
    priceCents: 4590,
    materials: ['Steel'],
    colour: 'Black',
    dimensions: 'H 180 cm',
    weight: '3.2 kg',
    care: 'Clean feeders fortnightly with warm water.',
    shippingClass: 'STANDARD',
    imageKey: 'garden-torch',
    badge: 'Popular',
    copy: {
      intro: 'A full feeding station in one afternoon — seed, peanuts and water for the whole neighbourhood.',
      benefits: ['Three feeder types bring different birds', 'Height-adjustable pole and ground spike', 'Mesh trays are quick to empty and wash'],
      use: 'Lawns, borders and anywhere with a clear view from the kitchen window.',
    },
    matchKeywords: ['bird feeder', 'bird station', 'wild bird feeder'],
  },
  {
    key: 'garden-tool-set-bamboo',
    name: 'Bamboo Garden Tool Set',
    subtitle: '5 tools + jute tote',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden', 'balcony'],
    styles: ['natural', 'scandinavian'],
    collections: ['green-living', 'weekend-refresh'],
    priceCents: 3490,
    materials: ['Bamboo', 'Steel', 'Jute'],
    colour: 'Natural',
    dimensions: 'Tools 30 cm · tote 40 × 30 cm',
    weight: '1.4 kg',
    care: 'Rinse tools after use; oil the bamboo handles monthly.',
    shippingClass: 'SMALL',
    imageKey: 'decorative-tray',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'Five everyday tools with bamboo handles and a jute tote that hangs by the door.',
      benefits: ['Everything a balcony or bed garden needs', 'Bamboo handles feel warm in cold hands', 'Tote keeps it all in one grab-and-go place'],
      use: 'Planting, potting and weekend tidying.',
    },
    matchKeywords: ['garden tool set', 'bamboo garden tools'],
  },
  {
    key: 'solar-water-feature',
    name: 'Solar Water Fountain',
    subtitle: 'Battery backup · 3 spray patterns',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden', 'terrace', 'balcony'],
    styles: ['modern', 'organic'],
    collections: ['garden-glow', 'balcony-escape'],
    priceCents: 3990,
    materials: ['Acrylic', 'Steel'],
    colour: 'Black',
    dimensions: 'Ø 16 cm pump · floats',
    weight: '0.6 kg',
    care: 'Rinse the pump monthly; keep the panel clear of debris.',
    battery: true,
    shippingClass: 'SMALL',
    imageKey: 'solar-lantern',
    copy: {
      intro: 'A floating solar fountain that turns any bowl or barrel into the calming sound of water.',
      benefits: ['Runs on sun with a battery for cloudy hours', 'Three spray heights for bowls and ponds', 'No wiring, no plumbing — drop it in'],
      use: 'Bird baths, barrels and garden bowls.',
    },
    matchKeywords: ['solar fountain', 'solar water feature', 'bird bath fountain'],
  },
  {
    key: 'lantern-brass-candle',
    name: 'Brass Candle Lantern',
    subtitle: 'H 30 cm · glass panels',
    category: 'garden',
    subcategories: ['lanterns'],
    spaces: ['garden', 'balcony', 'terrace'],
    styles: ['mediterranean', 'rustic-modern'],
    collections: ['garden-glow', 'mediterranean-garden'],
    priceCents: 2490,
    materials: ['Metal', 'Glass'],
    colour: 'Brass',
    dimensions: '14 × 14 × 30 cm',
    weight: '1.1 kg',
    care: 'Wipe the glass; bring indoors during storms.',
    shippingClass: 'FRAGILE',
    imageKey: 'solar-lantern',
    variants: [
      { type: 'size', name: 'H 30 cm', value: '30' },
      { type: 'size', name: 'H 45 cm', value: '45', deltaCents: 1200 },
    ],
    copy: {
      intro: 'A warm brass lantern with clear glass panels — candlelight that survives the breeze.',
      benefits: ['Glass panels keep flames steady outdoors', 'Carry ring for hooks, tables and steps', 'Ages to a soft golden patina'],
      use: 'Table centres, steps and balcony rails.',
    },
    matchKeywords: ['candle lantern', 'brass lantern', 'garden lantern candle'],
  },
  {
    key: 'herb-spiral-planter-kit',
    name: 'Herb Spiral Kit',
    subtitle: '3-tier cedar-look planter',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden', 'balcony', 'kitchen'],
    styles: ['rustic-modern', 'natural'],
    collections: ['green-living', 'small-spaces'],
    priceCents: 5990,
    materials: ['Wood composite'],
    colour: 'Brown',
    dimensions: 'Ø 60 × 55 cm',
    weight: '7.8 kg',
    care: 'Wipe clean; line the tiers before filling with soil.',
    shippingClass: 'HEAVY',
    imageKey: 'herb-pots',
    badge: 'Featured',
    featured: true,
    copy: {
      intro: 'A spiral of herbs by the kitchen door — three tiers, twelve plants, one weekend build.',
      benefits: ['Tall footprint grows more in less space', 'Drainage flows top tier to bottom', 'Weatherboard look suits patios and plots'],
      use: 'Kitchen doors, patios and sunny corners.',
    },
    matchKeywords: ['herb planter', 'tiered planter', 'herb spiral'],
  },
  {
    key: 'garden-kneeler-set',
    name: 'Garden Kneeler & Pad Set',
    subtitle: 'Foldable steel + memory foam',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden'],
    styles: ['modern', 'practical'],
    collections: ['weekend-refresh', 'modern-essentials'],
    priceCents: 3990,
    materials: ['Steel', 'Polyester'],
    colour: 'Green',
    dimensions: '60 × 33 × 50 cm folded 5 cm',
    weight: '2.8 kg',
    care: 'Wipe the foam; dry steel legs before storing.',
    shippingClass: 'STANDARD',
    imageKey: 'decorative-tray',
    copy: {
      intro: 'A kneeler that flips into a seat — knees and back, both looked after in one go.',
      benefits: ['Two heights: kneel low or sit higher', 'Memory foam takes the pressure off joints', 'Folds flat behind a shed door'],
      use: 'Beds, borders and long planting afternoons.',
    },
    matchKeywords: ['garden kneeler', 'garden seat pad'],
  },
  {
    key: 'wind-spinner-garden',
    name: 'Copper Garden Spinner',
    subtitle: 'Kinetic wind sculpture · H 75 cm',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden'],
    styles: ['modern', 'organic'],
    collections: ['natural-objects', 'statement-pieces'],
    priceCents: 4990,
    materials: ['Metal'],
    colour: 'Brass',
    dimensions: 'Ø 25 × 75 cm',
    weight: '1.6 kg',
    care: 'Copper weathers naturally; wipe with a dry cloth if desired.',
    shippingClass: 'STANDARD',
    imageKey: 'garden-torch',
    copy: {
      intro: 'A slow-spinning copper sculpture that catches every breeze — movement where flowers rest.',
      benefits: ['Silent spin on sealed bearings', 'Stakes firmly into beds and lawns', 'Copper catch-light works all day'],
      use: 'Borders, lawns and the corner that needs life.',
    },
    matchKeywords: ['wind spinner', 'garden spinner', 'kinetic garden'],
  },
  {
    key: 'balcony-railing-planter',
    name: 'Railing Planter Box',
    subtitle: 'Fits rails to 6 cm · 60 cm',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['balcony'],
    styles: ['scandinavian', 'modern'],
    collections: ['balcony-escape', 'green-living'],
    priceCents: 2990,
    materials: ['Steel'],
    colour: 'Black',
    dimensions: '60 × 18 × 16 cm',
    weight: '1.9 kg',
    care: 'Drill-free clamps adjust by hand; rinse seasonally.',
    shippingClass: 'SMALL',
    imageKey: 'palm-planter',
    badge: 'Popular',
    variants: [
      { type: 'size', name: '60 cm', value: '60' },
      { type: 'size', name: '80 cm', value: '80', deltaCents: 1000 },
    ],
    copy: {
      intro: 'A rail-hugging planter box that turns balcony fences into a summer border.',
      benefits: ['Clamps on without drilling', 'Drainage holes and plugs included', 'Powder-coated steel shrugs off weather'],
      use: 'Balcony rails, fence tops and window ledges.',
    },
    matchKeywords: ['railing planter', 'balcony planter', 'fence planter'],
  },
  {
    key: 'garden-hose-bundle',
    name: 'Cotton Hose & Brass Nozzle',
    subtitle: '15 m cotton-braided hose',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden', 'balcony'],
    styles: ['natural', 'modern'],
    collections: ['green-living', 'weekend-refresh'],
    priceCents: 4990,
    materials: ['Cotton', 'Brass'],
    colour: 'Green',
    dimensions: '15 m · Ø 12 mm',
    weight: '3.4 kg',
    care: 'Drain after use; store coiled in shade.',
    shippingClass: 'STANDARD',
    imageKey: 'decorative-tray',
    copy: {
      intro: 'A cotton-braided hose that coils neatly and a solid brass nozzle that feels like it should.',
      benefits: ['No kinks, no tangles — just water', 'Brass nozzle with mist to jet settings', 'Looks too good to hide in a box'],
      use: 'Terraces, balconies and tidy gardens.',
    },
    matchKeywords: ['garden hose', 'cotton hose', 'brass nozzle'],
  },
  {
    key: 'insect-hotel-natural',
    name: 'Bee & Insect Hotel',
    subtitle: 'Natural bamboo & pine · H 35 cm',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden', 'balcony'],
    styles: ['natural', 'rustic-modern'],
    collections: ['green-living', 'natural-objects'],
    priceCents: 2490,
    materials: ['Bamboo', 'Wood composite'],
    colour: 'Natural',
    dimensions: '22 × 8 × 35 cm',
    weight: '1.2 kg',
    care: 'Mount facing morning sun; replace canes seasonally.',
    shippingClass: 'SMALL',
    imageKey: 'seagrass-basket',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'A shelter for solitary bees and garden helpers — small holes, big difference.',
      benefits: ['Mixed tunnel sizes suit many species', 'Bamboo canes are easy to refresh', 'Roof overhang keeps chambers dry'],
      use: 'Fences, walls and sunny, sheltered spots.',
    },
    matchKeywords: ['insect hotel', 'bee hotel', 'bug house'],
  },
  {
    key: 'solar-lantern-garland',
    name: 'Solar Lantern Garland',
    subtitle: '6 mini lanterns · warm white',
    category: 'garden',
    subcategories: ['lanterns'],
    spaces: ['garden', 'balcony', 'terrace'],
    styles: ['mediterranean', 'organic'],
    collections: ['garden-glow', 'balcony-escape'],
    priceCents: 2690,
    materials: ['Metal', 'Polyester'],
    colour: 'Black',
    dimensions: '180 cm total · 6 lanterns',
    weight: '0.8 kg',
    care: 'Keep the solar box facing the sky; wipe panels monthly.',
    battery: true,
    shippingClass: 'SMALL',
    imageKey: 'solar-lantern',
    copy: {
      intro: 'Six mini lanterns on one solar garland — a Moroccan evening, no wiring required.',
      benefits: ['Lantern shapes cast patterned shadows', 'Two modes: steady glow or soft flicker', 'Drapes pergolas, rails and shrubs'],
      use: 'Pergola beams, balcony rails and hedges.',
    },
    matchKeywords: ['solar garland', 'lantern string', 'moroccan lights'],
  },
  {
    key: 'raised-bed-compact',
    name: 'Compact Raised Bed',
    subtitle: 'Cedar-look composite · 80 × 40 cm',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden', 'terrace'],
    styles: ['rustic-modern', 'modern'],
    collections: ['green-living', 'small-spaces'],
    priceCents: 6990,
    materials: ['Wood composite'],
    colour: 'Brown',
    dimensions: '80 × 40 × 30 cm',
    weight: '10.5 kg',
    care: 'Wipe down seasonally; composite needs no sealing.',
    shippingClass: 'HEAVY',
    imageKey: 'raised-planter',
    badge: 'Popular',
    copy: {
      intro: 'A waist-height veggie patch for patios — tomatoes at arm’s reach, weeds at a disadvantage.',
      benefits: ['Open base drains straight into the bed', 'Composite boards never rot or splinter', 'Assembles in twenty minutes with two tools'],
      use: 'Patios, balconies and small kitchen gardens.',
    },
    matchKeywords: ['raised bed', 'raised planter', 'vegetable bed'],
  },
  {
    key: 'globe-solar-stake-amber',
    name: 'Amber Globe Solar Stake',
    subtitle: 'Hand-blown look · warm amber',
    category: 'garden',
    subcategories: ['garden-decoration'],
    spaces: ['garden', 'balcony'],
    styles: ['organic', 'mediterranean'],
    collections: ['garden-glow', 'mediterranean-garden'],
    priceCents: 2190,
    materials: ['Glass', 'Steel'],
    colour: 'Gold',
    dimensions: 'Ø 12 cm globe · H 80 cm stake',
    weight: '0.7 kg',
    care: 'Wipe the globe; bring indoors before hard frost.',
    battery: true,
    shippingClass: 'FRAGILE',
    imageKey: 'solar-lantern',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'An amber glass globe that glows like late sun — the garden’s last warm light of the day.',
      benefits: ['Amber tone is gentler than white solar light', 'Stakes securely into beds and pots', 'Auto dusk-to-dawn sensor'],
      use: 'Among grasses, along paths and in tall pots.',
    },
    matchKeywords: ['solar globe stake', 'amber solar light', 'glass solar stake'],
  },
];

export const OUTDOOR: Archetype[] = [
  {
    key: 'outdoor-lounge-sofa',
    name: 'Portico Outdoor Lounge Sofa',
    subtitle: '3-seat · acacia frame · sand cushions',
    category: 'outdoor',
    subcategories: ['outdoor-furniture'],
    spaces: ['garden', 'terrace', 'patio'],
    styles: ['mediterranean', 'modern', 'organic'],
    collections: ['outdoor-living', 'statement-pieces'],
    priceCents: 24990,
    materials: ['Acacia', 'Polyester'],
    colour: 'Sand',
    dimensions: '196 × 82 × 78 cm',
    weight: '34 kg',
    care: 'Cover or store cushions between seasons; oil the frame yearly.',
    shippingClass: 'HEAVY',
    imageKey: 'outdoor-sofa',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    copy: {
      intro: 'A generous three-seat lounge in solid acacia with deep, quick-dry cushions — the garden’s living room.',
      benefits: ['Solid acacia frame seasons gracefully outdoors', 'Deep seats with removable, washable covers', 'Low profile frames the view, not the furniture'],
      use: 'Terraces, covered patios and poolside walls.',
    },
    matchKeywords: ['outdoor sofa', 'garden lounge sofa', 'patio sofa'],
  },
  {
    key: 'rattan-outdoor-armchair',
    name: 'Riviera Rattan Armchair',
    subtitle: 'All-weather rattan · cream cushion',
    category: 'outdoor',
    subcategories: ['outdoor-furniture'],
    spaces: ['garden', 'terrace', 'balcony'],
    styles: ['mediterranean', 'organic', 'natural'],
    collections: ['outdoor-living', 'balcony-escape'],
    priceCents: 9990,
    materials: ['Polyester', 'Steel'],
    colour: 'Natural',
    dimensions: '66 × 74 × 80 cm',
    weight: '7.6 kg',
    care: 'Wipe the weave with a damp cloth; store cushions dry.',
    shippingClass: 'STANDARD',
    imageKey: 'rattan-chair',
    badge: 'Featured',
    featured: true,
    copy: {
      intro: 'Woven all-weather rattan with a deep cream cushion — café mornings and aperitivo evenings.',
      benefits: ['Weave handles sun and showers', 'Light enough to follow the sun', 'Stacks two-high in winter storage'],
      use: 'Balconies, terraces and garden corners.',
    },
    matchKeywords: ['rattan outdoor chair', 'garden armchair', 'outdoor rattan'],
  },
  {
    key: 'bistro-set-round',
    name: 'Café Bistro Set',
    subtitle: 'Table + 2 chairs · powder-coated steel',
    category: 'outdoor',
    subcategories: ['outdoor-furniture'],
    spaces: ['balcony', 'patio'],
    styles: ['mediterranean', 'rustic-modern'],
    collections: ['balcony-escape', 'small-spaces'],
    priceCents: 15990,
    materials: ['Steel'],
    colour: 'Green',
    dimensions: 'Table Ø 60 × 72 cm · chairs 42 × 50 × 86 cm',
    weight: '14 kg',
    care: 'Wipe with a damp cloth; touch up chips to prevent rust.',
    shippingClass: 'HEAVY',
    imageKey: 'bistro-set',
    badge: 'Popular',
    isBestSeller: true,
    copy: {
      intro: 'A classic three-piece bistro set sized for balconies — morning coffee, done properly.',
      benefits: ['Round table tucks two chairs neatly', 'Foldable chairs store flat when needed', 'Powder coating handles city weather'],
      use: 'Balconies, small patios and front steps.',
    },
    matchKeywords: ['bistro set', 'balcony table chairs', 'patio bistro'],
  },
  {
    key: 'teak-bench-150',
    name: 'Teak Garden Bench',
    subtitle: 'Solid teak · 150 cm',
    category: 'outdoor',
    subcategories: ['outdoor-furniture'],
    spaces: ['garden', 'entrance'],
    styles: ['natural', 'rustic-modern', 'scandinavian'],
    collections: ['outdoor-living', 'warm-oak'],
    priceCents: 21990,
    materials: ['Teak'],
    colour: 'Brown',
    dimensions: '150 × 48 × 88 cm',
    weight: '21 kg',
    care: 'Teak silvers naturally; sand lightly to restore the honey tone.',
    shippingClass: 'HEAVY',
    imageKey: 'teak-bench',
    badge: "Editor's Pick",
    featured: true,
    copy: {
      intro: 'Solid teak, simple lines, fifty summers — a bench that becomes part of the garden.',
      benefits: ['Grade-A teak needs no cover or fuss', 'Slatted seat drains after rain', 'Suits lawns, porches and potting corners'],
      use: 'Under trees, beside gates and along paths.',
    },
    matchKeywords: ['teak bench', 'garden bench', 'wooden bench'],
  },
  {
    key: 'parasol-crank-2.7',
    name: 'Garden Parasol 2.7 m',
    subtitle: 'Crank & tilt · cream canopy',
    category: 'outdoor',
    subcategories: ['outdoor-furniture'],
    spaces: ['garden', 'terrace', 'patio'],
    styles: ['mediterranean', 'modern'],
    collections: ['outdoor-living', 'weekend-refresh'],
    priceCents: 9990,
    materials: ['Aluminium', 'Polyester'],
    colour: 'Cream',
    dimensions: 'Ø 270 cm · H 250 cm',
    weight: '6.5 kg',
    care: 'Close in wind; sponge-clean the canopy with mild soap.',
    shippingClass: 'OVERSIZED',
    imageKey: 'parasol',
    isNew: true,
    badge: 'New',
    copy: {
      intro: 'A generous cream parasol with crank and tilt — shade that follows the sun across lunch.',
      benefits: ['Easy crank lift, six tilt positions', 'UV-filtering canopy with air vent', 'Fits standard 25 kg bases (sold separately)'],
      use: 'Dining sets, loungers and lawn corners.',
    },
    matchKeywords: ['garden parasol', 'patio umbrella', 'sun parasol'],
  },
  {
    key: 'outdoor-dining-table-oak',
    name: 'Al Fresco Dining Table',
    subtitle: 'Weather-treated oak-look · 6 seats',
    category: 'outdoor',
    subcategories: ['outdoor-furniture'],
    spaces: ['garden', 'terrace'],
    styles: ['modern', 'natural'],
    collections: ['outdoor-living', 'modern-essentials'],
    priceCents: 19990,
    materials: ['Wood composite', 'Steel'],
    colour: 'Oak',
    dimensions: '150 × 90 × 74 cm',
    weight: '28 kg',
    care: 'Wipe with soapy water; no annual sealing required.',
    shippingClass: 'HEAVY',
    imageKey: 'outdoor-sofa',
    copy: {
      intro: 'A six-seat outdoor table with the warmth of oak and the upkeep of plastic — long lunches, zero guilt.',
      benefits: ['Composite top shrugs off spills and sun', 'Powder-coated steel legs stay put', 'Umbrella hole centred for midsummer lunches'],
      use: 'Terraces, lawns and conservatory edges.',
    },
    matchKeywords: ['outdoor dining table', 'garden table', 'patio table'],
  },
  {
    key: 'sun-lounger-reclining',
    name: 'Reclining Sun Lounger',
    subtitle: '5 positions · olefin sling · sage',
    category: 'outdoor',
    subcategories: ['outdoor-furniture'],
    spaces: ['garden', 'patio'],
    styles: ['modern', 'mediterranean'],
    collections: ['outdoor-living', 'weekend-refresh'],
    priceCents: 12990,
    materials: ['Steel', 'Polyester'],
    colour: 'Green',
    dimensions: '165 × 60 × 92 cm',
    weight: '11 kg',
    care: 'Hose the sling occasionally; close flat before storing.',
    shippingClass: 'OVERSIZED',
    imageKey: 'rattan-chair',
    copy: {
      intro: 'Five positions from upright coffee to full Sunday nap, on a quick-dry sage sling.',
      benefits: ['Sling dries minutes after a shower', 'Wheels on the front legs for easy chasing of the sun', 'Folds nearly flat for winter'],
      use: 'Lawns, pool sides and sunny patios.',
    },
    matchKeywords: ['sun lounger', 'reclining lounger', 'deck chair'],
  },
  {
    key: 'outdoor-storage-bench',
    name: 'Deck Storage Bench',
    subtitle: '130 L · cushion-top seat',
    category: 'outdoor',
    subcategories: ['outdoor-furniture'],
    spaces: ['garden', 'terrace', 'balcony'],
    styles: ['modern', 'practical'],
    collections: ['outdoor-living', 'small-spaces'],
    priceCents: 8990,
    materials: ['Plywood', 'Polyester'],
    colour: 'Grey',
    dimensions: '110 × 50 × 52 cm',
    weight: '13 kg',
    care: 'Wipe clean; keep the latch dry.',
    shippingClass: 'HEAVY',
    imageKey: 'teak-bench',
    copy: {
      intro: 'A bench that swallows the cushions, the hose and the kids’ garden chaos — then offers a seat.',
      benefits: ['130 litres of hidden, dry storage', 'Cushioned top doubles as extra seating', 'Gas-lift lid opens with one hand'],
      use: 'Balconies, terraces and poolside.',
    },
    matchKeywords: ['outdoor storage bench', 'garden storage box'],
  },
  {
    key: 'fire-pit-table-low',
    name: 'Low Fire Table',
    subtitle: 'Gas fire bowl · slate top · Ø 80 cm',
    category: 'outdoor',
    subcategories: ['outdoor-furniture'],
    spaces: ['terrace', 'patio'],
    styles: ['modern', 'contemporary'],
    collections: ['outdoor-living', 'statement-pieces'],
    priceCents: 29990,
    materials: ['Steel', 'Stone'],
    colour: 'Grey',
    dimensions: 'Ø 80 × 45 cm',
    weight: '38 kg',
    care: 'Cover when not in use; check connections seasonally.',
    shippingClass: 'SPECIAL',
    imageKey: 'fire-pit',
    badge: "Editor's Pick",
    copy: {
      intro: 'A slate-topped fire table — coffee table by day, warm centrepiece after dark.',
      benefits: ['Instant flame with the turn of a dial', 'Lava stones included for the full effect', 'Doubles as a drinks and dining table'],
      use: 'Terrace seating circles and lounge sets.',
    },
    matchKeywords: ['fire table', 'gas fire pit', 'garden fire table'],
  },
  {
    key: 'hammock-cotton-stand',
    name: 'Cotton Hammock & Stand',
    subtitle: '2-person · ash stand · 200 kg',
    category: 'outdoor',
    subcategories: ['outdoor-furniture'],
    spaces: ['garden', 'terrace'],
    styles: ['organic', 'scandinavian'],
    collections: ['cosy-corner', 'weekend-refresh'],
    priceCents: 9990,
    materials: ['Cotton', 'Oak'],
    colour: 'Natural',
    dimensions: 'Stand 320 × 120 × 110 cm',
    weight: '17 kg',
    care: 'Machine wash the hammock; store the stand dry in winter.',
    shippingClass: 'HEAVY',
    imageKey: 'outdoor-sofa',
    copy: {
      intro: 'A proper two-person hammock on a curved ash stand — Sunday afternoons, upgraded.',
      benefits: ['No trees required — stand goes anywhere flat', '200 kg capacity for easy sharing', 'Cotton weave softens with every use'],
      use: 'Lawns, terraces and shadier garden corners.',
    },
    matchKeywords: ['hammock with stand', 'garden hammock'],
  },
  {
    key: 'outdoor-rug-flatweave',
    name: 'Indoor-Outdoor Flatweave Rug',
    subtitle: 'Recycled PET · stripe · 160 × 230 cm',
    category: 'outdoor',
    subcategories: [],
    spaces: ['terrace', 'balcony', 'patio'],
    styles: ['mediterranean', 'modern'],
    collections: ['outdoor-living', 'weekend-refresh'],
    priceCents: 7990,
    materials: ['Polyester'],
    colour: 'Sand',
    dimensions: '160 × 230 cm',
    weight: '4.2 kg',
    care: 'Shake out; hose clean and dry flat.',
    shippingClass: 'OVERSIZED',
    imageKey: 'outdoor-sofa',
    variants: [
      { type: 'size', name: '160 × 230 cm', value: '160-230' },
      { type: 'size', name: '200 × 300 cm', value: '200-300', deltaCents: 4000 },
    ],
    copy: {
      intro: 'A woven PET rug that defines an outdoor room — soft underfoot, fearless about weather.',
      benefits: ['Made from recycled bottles, quick to dry', 'Flatweave lies flat under door thresholds', 'Sand stripe suits every cushion collection'],
      use: 'Under lounge sets, bistro tables and tents of fairy lights.',
    },
    matchKeywords: ['outdoor rug', 'flatweave rug', 'recycled rug'],
  },
  {
    key: 'outdoor-cushion-waterproof',
    name: 'Outdoor Floor Cushions',
    subtitle: 'Set of 2 · water-repellent · olive',
    category: 'outdoor',
    subcategories: [],
    spaces: ['garden', 'balcony', 'terrace'],
    styles: ['organic', 'mediterranean'],
    collections: ['outdoor-living', 'cosy-corner'],
    priceCents: 4990,
    materials: ['Polyester'],
    colour: 'Olive',
    dimensions: '60 × 60 × 12 cm each',
    weight: '2.6 kg',
    care: 'Wipe dry after rain; unzip and air monthly.',
    shippingClass: 'STANDARD',
    imageKey: 'linen-cushions',
    badge: 'Popular',
    copy: {
      intro: 'Two big, weather-happy floor cushions that turn terrace decking into the best seat in the house.',
      benefits: ['Water-repellent shell beads off showers', 'Generous 12 cm fill for real lounging', 'Handles make them easy to carry and hang'],
      use: 'Decking, lawn picnics and balcony corners.',
    },
    matchKeywords: ['outdoor floor cushions', 'patio cushions'],
  },
];

export const PLANTERS: Archetype[] = [
  {
    key: 'ceramic-ribbed-planter',
    name: 'Ribbed Stone Planter',
    subtitle: 'Stone-effect · indoor & outdoor · Ø 32 cm',
    category: 'planters',
    subcategories: ['pots'],
    spaces: ['living-room', 'garden', 'balcony'],
    styles: ['organic', 'modern', 'natural'],
    collections: ['green-living', 'natural-objects'],
    priceCents: 4490,
    materials: ['Fibre stone'],
    colour: 'Grey',
    dimensions: 'Ø 32 × 30 cm',
    weight: '4.8 kg',
    care: 'Frost-resistant; wipe clean; drainage hole included.',
    shippingClass: 'HEAVY',
    imageKey: 'ceramic-planter',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    variants: [
      { type: 'size', name: 'Ø 32 cm', value: '32' },
      { type: 'size', name: 'Ø 42 cm', value: '42', deltaCents: 2000 },
    ],
    copy: {
      intro: 'A softly ribbed stone-effect planter that flatters ferns indoors and olives out.',
      benefits: ['Fibre stone is light to lift, heavy to look at', 'Frost-resistant for year-round displaying', 'Drainage hole plugs included for indoor use'],
      use: 'Statement plants in living rooms and patios.',
    },
    matchKeywords: ['stone planter', 'fibre stone pot', 'large plant pot'],
  },
  {
    key: 'terracotta-pot-set',
    name: 'Terracotta Pot Set',
    subtitle: 'Set of 3 · classic clay',
    category: 'planters',
    subcategories: ['pots'],
    spaces: ['garden', 'balcony'],
    styles: ['mediterranean', 'rustic-modern'],
    collections: ['mediterranean-garden', 'green-living'],
    priceCents: 2990,
    materials: ['Ceramic'],
    colour: 'Terracotta',
    dimensions: 'Ø 12 / 16 / 20 cm',
    weight: '2.7 kg',
    care: 'Clay breathes — expect charming patina; empty before frost.',
    shippingClass: 'FRAGILE',
    imageKey: 'herb-pots',
    badge: 'Popular',
    copy: {
      intro: 'Three classic clay pots in stepping sizes — the quiet heroes of every windowsill and step.',
      benefits: ['Breathable clay keeps roots happy', 'Stepped set styles shelves instantly', 'Saucers available to match'],
      use: 'Herbs, bulbs and small evergreens.',
    },
    matchKeywords: ['terracotta pots', 'clay pot set', 'flower pots'],
  },
  {
    key: 'self-watering-planter-tall',
    name: 'Self-Watering Tower Planter',
    subtitle: 'H 55 cm · 3-week reservoir',
    category: 'planters',
    subcategories: ['pots'],
    spaces: ['living-room', 'home-office'],
    styles: ['modern', 'contemporary'],
    collections: ['green-living', 'modern-essentials'],
    priceCents: 5990,
    materials: ['Acrylic'],
    colour: 'White',
    dimensions: 'Ø 26 × 55 cm',
    weight: '2.9 kg',
    care: 'Refill the reservoir when the gauge drops; wipe the matte shell.',
    shippingClass: 'STANDARD',
    imageKey: 'palm-planter',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'Three weeks of holiday-proof watering for your tallest plant — with a gauge that does the worrying.',
      benefits: ['Reservoir feeds roots from below', 'Water level gauge takes the guesswork out', 'Lightweight shell suits upper floors'],
      use: 'Monsteras, figs and palms at home or the office.',
    },
    matchKeywords: ['self watering planter', 'tall plant pot'],
  },
  {
    key: 'hanging-macrame-planter',
    name: 'Macramé Hanging Planter',
    subtitle: 'Natural cotton cord · pot included',
    category: 'planters',
    subcategories: ['pots'],
    spaces: ['balcony', 'bedroom', 'living-room'],
    styles: ['boho', 'organic', 'natural'],
    collections: ['small-spaces', 'green-living'],
    priceCents: 1990,
    materials: ['Cotton', 'Ceramic'],
    colour: 'Natural',
    dimensions: 'Cord 70 cm · pot Ø 15 cm',
    weight: '0.7 kg',
    care: 'Spot-clean the cord; water plants in place with a narrow spout.',
    shippingClass: 'SMALL',
    imageKey: 'palm-planter',
    badge: 'Popular',
    copy: {
      intro: 'Hand-knotted cotton and a matte pot — trailing plants, finally off the shelf.',
      benefits: ['Frees surfaces for small spaces', 'Adjustable cord length at the tie', 'Ceramic pot lifts out for repotting'],
      use: 'Curtain rails, hooks and balcony ceilings.',
    },
    matchKeywords: ['hanging planter', 'macrame planter', 'hanging pot'],
  },
  {
    key: 'oak-planter-box-window',
    name: 'Oak-Look Window Planter',
    subtitle: '72 cm · zinc liner',
    category: 'planters',
    subcategories: ['pots'],
    spaces: ['kitchen', 'balcony'],
    styles: ['scandinavian', 'rustic-modern'],
    collections: ['green-living', 'weekend-refresh'],
    priceCents: 3490,
    materials: ['Wood composite', 'Metal'],
    colour: 'Oak',
    dimensions: '72 × 18 × 16 cm',
    weight: '3.1 kg',
    care: 'Lift out the zinc liner for cleaning and planting.',
    shippingClass: 'STANDARD',
    imageKey: 'herb-pots',
    copy: {
      intro: 'A warm oak-look trough with a proper zinc liner — herbs on the sill, flowers on the rail.',
      benefits: ['Removable liner keeps timber dry', 'Fits most window sills and rails', 'Drill-free brackets included'],
      use: 'Kitchen windows, balcony rails and shed windows.',
    },
    matchKeywords: ['window planter', 'herb window box'],
  },
  {
    key: 'concrete-succulent-bowls',
    name: 'Concrete Succulent Bowls',
    subtitle: 'Set of 3 · matte grey',
    category: 'planters',
    subcategories: ['pots'],
    spaces: ['home-office', 'living-room'],
    styles: ['modern', 'industrial'],
    collections: ['small-spaces', 'modern-essentials'],
    priceCents: 2490,
    materials: ['Concrete'],
    colour: 'Grey',
    dimensions: 'Ø 10 / 12 / 14 cm',
    weight: '1.8 kg',
    care: 'Wipe clean; use a liner for watering.',
    shippingClass: 'STANDARD',
    imageKey: 'herb-pots',
    copy: {
      intro: 'Little concrete bowls with big design energy — cacti, succulents and desk-side calm.',
      benefits: ['Hand-cast concrete, each one unique', 'Nesting sizes style a desk in a minute', 'Rubber feet protect surfaces'],
      use: 'Desks, windowsills and shelf clusters.',
    },
    matchKeywords: ['concrete planters', 'succulent pots'],
  },
  {
    key: 'tall-fibreglass-olive-pot',
    name: 'Tall Olive Tree Pot',
    subtitle: 'Fibreglass · H 65 cm · olive green',
    category: 'planters',
    subcategories: ['pots'],
    spaces: ['garden', 'terrace', 'entrance'],
    styles: ['mediterranean', 'modern'],
    collections: ['mediterranean-garden', 'green-living'],
    priceCents: 6990,
    materials: ['Acrylic'],
    colour: 'Olive',
    dimensions: 'Ø 40 × 65 cm',
    weight: '6.2 kg',
    care: 'Frost-proof shell; rinse and wipe seasonally.',
    shippingClass: 'HEAVY',
    imageKey: 'palm-planter',
    badge: "Editor's Pick",
    copy: {
      intro: 'A tall, tapered pot in deep olive green — made for olive trees, bays and dramatic grasses.',
      benefits: ['Fibreglass is strong yet two-person light', 'Deep volume suits long-rooted trees', 'Colour-fast finish through seasons'],
      use: 'Entrances, terrace corners and pool edges.',
    },
    matchKeywords: ['tall outdoor planter', 'fibreglass pot', 'olive tree pot'],
  },
  {
    key: 'stackable-herb-tower',
    name: 'Stackable Herb Tower',
    subtitle: '3 stackable tiers · self-draining',
    category: 'planters',
    subcategories: ['pots'],
    spaces: ['balcony', 'kitchen'],
    styles: ['modern', 'practical'],
    collections: ['small-spaces', 'green-living'],
    priceCents: 2990,
    materials: ['Acrylic'],
    colour: 'Green',
    dimensions: 'Ø 30 × 45 cm stacked',
    weight: '1.9 kg',
    care: 'Rotate tiers for even sun; rinse between plantings.',
    shippingClass: 'SMALL',
    imageKey: 'herb-pots',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'Nine herbs in one square metre — stack, plant, water the top and dinner is seasoned.',
      benefits: ['Water trickles through every tier', 'Grows up, not out — balcony friendly', 'Tool-free stacking in seconds'],
      use: 'Balconies, patios and kitchen doors.',
    },
    matchKeywords: ['herb tower', 'stackable planters', 'vertical planter'],
  },
  {
    key: 'woven-seagrass-planter-basket',
    name: 'Seagrass Planter Basket',
    subtitle: 'Hand-woven · 26 cm · liner included',
    category: 'planters',
    subcategories: ['pots'],
    spaces: ['living-room', 'bedroom'],
    styles: ['natural', 'organic', 'boho'],
    collections: ['natural-objects', 'cosy-corner'],
    priceCents: 2190,
    materials: ['Seagrass', 'Plastic'],
    colour: 'Natural',
    dimensions: 'Ø 26 × 24 cm',
    weight: '0.9 kg',
    care: 'Keep the inner liner in place when watering; dust the weave.',
    shippingClass: 'SMALL',
    imageKey: 'seagrass-basket',
    badge: 'Best Seller',
    isBestSeller: true,
    copy: {
      intro: 'Woven seagrass with a hidden liner — nursery pots disappear, texture stays.',
      benefits: ['Hides plastic pots beautifully', 'Feather-light for shelf styling', 'Handles make plant moves easy'],
      use: 'Pothos, ferns and calatheas indoors.',
    },
    matchKeywords: ['seagrass planter', 'woven basket planter', 'plant basket'],
  },
  {
    key: 'grow-bag-set-fabric',
    name: 'Fabric Grow Bag Set',
    subtitle: 'Set of 5 · handles · 25 L each',
    category: 'planters',
    subcategories: ['pots'],
    spaces: ['garden', 'terrace'],
    styles: ['practical', 'rustic-modern'],
    collections: ['green-living', 'weekend-refresh'],
    priceCents: 2490,
    materials: ['Polyester'],
    colour: 'Green',
    dimensions: 'Ø 35 × 30 cm each',
    weight: '1.5 kg',
    care: 'Empty and air-dry at season end; machine washable.',
    shippingClass: 'STANDARD',
    imageKey: 'raised-planter',
    copy: {
      intro: 'Five breathable fabric bags that grow better tomatoes than pots — ask any root.',
      benefits: ['Air-pruned roots mean stronger plants', 'Folds flat for storage between seasons', 'Reinforced handles for moving in sun'],
      use: 'Tomatoes, potatoes, salads and dahlias.',
    },
    matchKeywords: ['grow bags', 'fabric pots', 'potato bags'],
  },
];

export const OUTDOOR_PRIVACY: Archetype[] = [
  {
    key: 'slatted-privacy-screen',
    name: 'Slatted Privacy Screen',
    subtitle: 'WPC · 180 × 120 cm · oak',
    category: 'outdoor-privacy',
    subcategories: ['privacy-screens'],
    spaces: ['balcony', 'terrace', 'garden'],
    styles: ['modern', 'natural'],
    collections: ['outdoor-living', 'wall-makeover'],
    priceCents: 12990,
    materials: ['WPC'],
    colour: 'Oak',
    dimensions: '180 × 120 × 4 cm',
    weight: '18 kg',
    care: 'Rinse occasionally; composite needs no staining.',
    shippingClass: 'HEAVY',
    imageKey: 'privacy-screen',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    copy: {
      intro: 'A freestanding slatted screen that turns a fishbowl balcony into a private outdoor room.',
      benefits: ['Weather-proof composite — no annual painting', 'Horizontal slats filter wind and views', 'Freestanding feet or wall-fix, your choice'],
      use: 'Balcony edges, hot tubs and terrace dining.',
    },
    matchKeywords: ['privacy screen', 'balcony privacy', 'garden screen'],
  },
  {
    key: 'artificial-hedge-panel',
    name: 'Instant Hedge Panel',
    subtitle: 'UV-stable leaf · 100 × 100 cm',
    category: 'outdoor-privacy',
    subcategories: ['privacy-screens'],
    spaces: ['balcony', 'garden'],
    styles: ['modern', 'practical'],
    collections: ['green-living', 'weekend-refresh'],
    priceCents: 4990,
    materials: ['Polyester', 'Steel'],
    colour: 'Green',
    dimensions: '100 × 100 cm · connectable',
    weight: '3.4 kg',
    care: 'Rinse with water in spring; UV-stable foliage.',
    shippingClass: 'STANDARD',
    imageKey: 'privacy-screen',
    badge: 'Popular',
    variants: [
      { type: 'pack', name: 'Single panel', value: 'single' },
      { type: 'pack', name: 'Set of 4', value: 'set-4', deltaCents: 14000 },
    ],
    copy: {
      intro: 'Lush, evergreen coverage in the time it takes to zip-tie four panels to a railing.',
      benefits: ['Connectable panels cover any length', 'UV-stable leaves keep their colour', 'Cuts with scissors for pipes and posts'],
      use: 'Railings, fences and ugly views.',
    },
    matchKeywords: ['artificial hedge', 'fake ivy panel', 'hedge screen'],
  },
  {
    key: 'bamboo-fence-roll',
    name: 'Rolled Bamboo Fence',
    subtitle: 'Natural cane · 400 × 150 cm',
    category: 'outdoor-privacy',
    subcategories: ['privacy-screens'],
    spaces: ['garden', 'balcony'],
    styles: ['natural', 'rustic-modern', 'japandi'],
    collections: ['japandi-calm', 'natural-objects'],
    priceCents: 5990,
    materials: ['Bamboo', 'Steel'],
    colour: 'Natural',
    dimensions: '400 × 150 cm roll',
    weight: '9.8 kg',
    care: 'Fix to existing fences with the supplied ties; oil yearly.',
    shippingClass: 'OVERSIZED',
    imageKey: 'privacy-screen',
    copy: {
      intro: 'Six metres of calm, rolled bamboo that hides bins, wires and next door’s trampoline.',
      benefits: ['Covers old fencing in one afternoon', 'Wire-bound canes stay straight for years', 'Cuts to height with a handsaw'],
      use: 'Fences, balcony sides and compost corners.',
    },
    matchKeywords: ['bamboo fence', 'bamboo screen roll', 'cane fence'],
  },
  {
    key: 'reed-screen-balcony',
    name: 'Reed Balcony Screen',
    subtitle: 'Natural reed · 300 × 100 cm',
    category: 'outdoor-privacy',
    subcategories: ['privacy-screens'],
    spaces: ['balcony'],
    styles: ['natural', 'organic'],
    collections: ['balcony-escape', 'natural-objects'],
    priceCents: 2990,
    materials: ['Bamboo', 'Steel'],
    colour: 'Natural',
    dimensions: '300 × 100 cm roll',
    weight: '4.1 kg',
    care: 'Attach with cable ties; replace after harsh winters.',
    shippingClass: 'STANDARD',
    imageKey: 'privacy-screen',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'A light, golden reed roll that gives balconies privacy without losing the breeze.',
      benefits: ['Filters light and wind gently', 'Weighs little — perfect for railings', 'Natural golden tone warms city views'],
      use: 'Balcony railings and rail-height gaps.',
    },
    matchKeywords: ['reed screening', 'balcony screen', 'reed fence'],
  },
  {
    key: 'trellis-climbing-frame',
    name: 'Climbing Plant Trellis',
    subtitle: 'Diamond trellis · 180 × 60 cm',
    category: 'outdoor-privacy',
    subcategories: ['privacy-screens'],
    spaces: ['garden', 'terrace'],
    styles: ['rustic-modern', 'natural'],
    collections: ['green-living', 'garden-glow'],
    priceCents: 3990,
    materials: ['Wood composite'],
    colour: 'Brown',
    dimensions: '180 × 60 × 3 cm',
    weight: '5.6 kg',
    care: 'Fix firmly before planting; wipe clean each spring.',
    shippingClass: 'OVERSIZED',
    imageKey: 'privacy-screen',
    copy: {
      intro: 'A diamond trellis waiting for jasmine — privacy you grow, season after season.',
      benefits: ['Supports climbers from year one', 'Composite slats never rot', 'Wall or post fixing, either orientation'],
      use: 'Fences, walls and seating-area backs.',
    },
    matchKeywords: ['garden trellis', 'climbing trellis', 'wall trellis'],
  },
  {
    key: 'planter-screen-combo',
    name: 'Planter & Screen Combo',
    subtitle: 'Trough + 90 cm slat back',
    category: 'outdoor-privacy',
    subcategories: ['privacy-screens'],
    spaces: ['balcony', 'terrace'],
    styles: ['modern', 'natural'],
    collections: ['green-living', 'outdoor-living'],
    priceCents: 9990,
    materials: ['Wood composite'],
    colour: 'Oak',
    dimensions: '120 × 40 × 150 cm',
    weight: '22 kg',
    care: 'Line the trough before soil; rinse the slats occasionally.',
    shippingClass: 'HEAVY',
    imageKey: 'privacy-screen',
    badge: "Editor's Pick",
    copy: {
      intro: 'Planter and privacy in one clever piece — grasses below, height above, neighbours forgotten.',
      benefits: ['Integrated trough waters your screen greenery', 'Slat back adds instant 150 cm of privacy', 'Freestanding and balcony-rail friendly'],
      use: 'Balcony edges, terrace divides and café corners.',
    },
    matchKeywords: ['planter screen', 'planter with trellis'],
  },
  {
    key: 'side-awning-retractable',
    name: 'Retractable Side Awning',
    subtitle: '1.8 × 3 m · sand',
    category: 'outdoor-privacy',
    subcategories: ['privacy-screens'],
    spaces: ['terrace', 'patio', 'garden'],
    styles: ['modern', 'mediterranean'],
    collections: ['outdoor-living', 'weekend-refresh'],
    priceCents: 8990,
    materials: ['Polyester', 'Aluminium'],
    colour: 'Sand',
    dimensions: '180 × 300 cm extended',
    weight: '9.2 kg',
    care: 'Retract in strong wind; sponge-clean the fabric.',
    shippingClass: 'HEAVY',
    imageKey: 'parasol',
    copy: {
      intro: 'A pull-out side awning — shade, windbreak and privacy that disappear when you want the view.',
      benefits: ['Extends to 3 m in seconds', 'UV- and water-resistant fabric', 'Freestanding with ground anchors'],
      use: 'Terraces, patios and pool sides.',
    },
    matchKeywords: ['side awning', 'retractable screen', 'privacy awning'],
  },
  {
    key: 'outdoor-curtain-panel',
    name: 'Outdoor Curtain Panel',
    subtitle: 'Water-repellent · 140 × 240 cm · oat',
    category: 'outdoor-privacy',
    subcategories: ['privacy-screens'],
    spaces: ['terrace', 'patio'],
    styles: ['mediterranean', 'organic'],
    collections: ['outdoor-living', 'soft-neutrals'],
    priceCents: 4990,
    materials: ['Polyester'],
    colour: 'Beige',
    dimensions: '140 × 240 cm',
    weight: '1.8 kg',
    care: 'Machine washable at 30°C; air dry to keep the coating.',
    shippingClass: 'STANDARD',
    imageKey: 'linen-cushions',
    badge: 'New',
    isNew: true,
    variants: [
      { type: 'size', name: '140 × 240 cm', value: '140-240' },
      { type: 'size', name: '140 × 300 cm', value: '140-300', deltaCents: 1500 },
    ],
    copy: {
      intro: 'A soft oat curtain for pergolas and gazebos — the indoor feeling, outdoors.',
      benefits: ['Water-repellent weave handles summer showers', 'Rust-proof eyelets for any rod or wire', 'Filters glare without darkening the space'],
      use: 'Pergolas, gazebos and covered balconies.',
    },
    matchKeywords: ['outdoor curtain', 'pergola curtain', 'gazebo curtains'],
  },
];
