// ============================================================
// E-com.casa — Curated demo catalogue:
//   ORGANISATION (7) + KITCHEN & DINING (5) +
//   GADGETS & SMART HOME (5) + ACCESSORIES (5)
// 100% original E-com.casa copy and merchandising data.
// ============================================================

import type { Archetype } from './types';

export const ORGANISATION: Archetype[] = [
  {
    key: 'seagrass-storage-baskets',
    name: 'Seagrass Storage Baskets',
    subtitle: 'Set of 3 · rope handles',
    category: 'organisation',
    subcategories: [],
    spaces: ['living-room', 'bedroom', 'bathroom'],
    styles: ['natural', 'organic', 'scandinavian'],
    collections: ['natural-objects', 'cosy-corner'],
    priceCents: 3990,
    materials: ['Seagrass'],
    colour: 'Natural',
    dimensions: 'Ø 28 / 34 / 40 cm',
    weight: '2.2 kg',
    care: 'Spot clean; keep dry; reshape by hand if needed.',
    shippingClass: 'STANDARD',
    imageKey: 'seagrass-basket',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    copy: {
      intro: 'Three hand-woven seagrass baskets that make tidy look like a design choice.',
      benefits: ['Nested sizes stack away when empty', 'Sturdy rope handles for real hauling', 'Hides everything from throws to toys'],
      use: 'Sofa sides, bedroom corners and bathroom shelves.',
    },
    matchKeywords: ['storage baskets', 'seagrass basket', 'woven basket'],
  },
  {
    key: 'oak-hallway-shelf-hooks',
    name: 'Hallway Shelf with Hooks',
    subtitle: 'Oak · shelf + 4 hooks · 70 cm',
    category: 'organisation',
    subcategories: [],
    spaces: ['entrance'],
    styles: ['scandinavian', 'japandi', 'natural'],
    collections: ['small-spaces', 'warm-oak'],
    priceCents: 5990,
    materials: ['Oak', 'Metal'],
    colour: 'Oak',
    dimensions: '70 × 18 × 22 cm',
    weight: '3.2 kg',
    care: 'Wipe with a dry cloth; hold 10 kg when firmly mounted.',
    shippingClass: 'STANDARD',
    imageKey: 'oak-wall-shelf',
    badge: 'Featured',
    featured: true,
    copy: {
      intro: 'One oak board, four matte hooks — keys, post, coats and the daily shuffle, solved.',
      benefits: ['Shelf and hooks in a single tidy unit', 'Solid oak carries real everyday weight', 'Two-anchor mount into studs or plugs'],
      use: 'Entrances, utility corners and home offices.',
    },
    matchKeywords: ['hallway shelf hooks', 'entryway organizer', 'coat shelf'],
  },
  {
    key: 'bamboo-wardrobe-organisers',
    name: 'Wardrobe Organiser Set',
    subtitle: '6 bamboo boxes · 3 sizes',
    category: 'organisation',
    subcategories: [],
    spaces: ['bedroom'],
    styles: ['japandi', 'scandinavian'],
    collections: ['japandi-calm', 'small-spaces'],
    priceCents: 3490,
    materials: ['Bamboo'],
    colour: 'Natural',
    dimensions: '30 × 20 × 12 cm etc.',
    weight: '2.0 kg',
    care: 'Wipe with a dry cloth; keep wardrobe ventilated.',
    shippingClass: 'STANDARD',
    imageKey: 'seagrass-basket',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'Six bamboo boxes that turn wardrobe chaos into calm, labelled rows.',
      benefits: ['Breathable bamboo keeps linens fresh', 'Open fronts see contents at a glance', 'Nesting sizes fit shelves and cubes'],
      use: 'Wardrobes, linen closets and under-bed rows.',
    },
    matchKeywords: ['wardrobe organizer', 'storage boxes bamboo', 'closet organizer'],
  },
  {
    key: 'under-sink-drawer-organiser',
    name: 'Under-Sink Organiser Drawer',
    subtitle: 'Pull-out two-tier · white',
    category: 'organisation',
    subcategories: [],
    spaces: ['kitchen', 'bathroom'],
    styles: ['modern', 'practical'],
    collections: ['small-spaces', 'modern-essentials'],
    priceCents: 2990,
    materials: ['Acrylic'],
    colour: 'White',
    dimensions: '38 × 24 × 32 cm',
    weight: '1.6 kg',
    care: 'Rinse trays by hand; wipe the frame dry.',
    shippingClass: 'SMALL',
    imageKey: 'decorative-tray',
    copy: {
      intro: 'The under-sink black hole, reorganized: slide out the top tier and everything comes to you.',
      benefits: ['Two tiers double the usable space', 'Slide-out top reaches the back row', 'Fits most standard sink cabinets'],
      use: 'Kitchens, bathrooms and utility rooms.',
    },
    matchKeywords: ['under sink organizer', 'pull out organizer'],
  },
  {
    key: 'ladder-shelf-4tier',
    name: 'Ladder Shelf',
    subtitle: '4-tier oak-look · 150 cm',
    category: 'organisation',
    subcategories: [],
    spaces: ['living-room', 'bathroom', 'home-office'],
    styles: ['scandinavian', 'modern'],
    collections: ['small-spaces', 'weekend-refresh'],
    priceCents: 7990,
    materials: ['Wood composite', 'Steel'],
    colour: 'Oak',
    dimensions: '60 × 36 × 150 cm',
    weight: '12 kg',
    care: 'Wipe shelves; check level feet after moving.',
    shippingClass: 'HEAVY',
    imageKey: 'oak-wall-shelf',
    copy: {
      intro: 'A leaning four-shelf ladder that climbs storage upward where floor space runs out.',
      benefits: ['Anti-tip strap included for safety', 'Shelves step wider toward the floor', 'Open sides keep small rooms airy'],
      use: 'Bathrooms, living rooms and reading corners.',
    },
    matchKeywords: ['ladder shelf', 'leaning shelf', 'display shelf'],
  },
  {
    key: 'wall-file-organiser-oak',
    name: 'Wall File Organiser',
    subtitle: 'Oak + steel · 3 slots',
    category: 'organisation',
    subcategories: [],
    spaces: ['home-office'],
    styles: ['modern', 'warm-minimal'],
    collections: ['home-office', 'small-spaces'],
    priceCents: 3490,
    materials: ['Oak', 'Steel'],
    colour: 'Oak',
    dimensions: '32 × 9 × 30 cm',
    weight: '1.3 kg',
    care: 'Dust with a dry cloth.',
    shippingClass: 'SMALL',
    imageKey: 'oak-wall-shelf',
    badge: 'Popular',
    copy: {
      intro: 'Three oak-backed slots that lift the paper mountain off the desk and onto the wall.',
      benefits: ['To-do, in-progress and done, finally visible', 'Frees desk surface completely', 'Mounts with two screws'],
      use: 'Home offices, kitchen posts and kids’ art.',
    },
    matchKeywords: ['wall file organizer', 'desk organizer wall'],
  },
  {
    key: 'storage-ottoman-pouf',
    name: 'Storage Pouf',
    subtitle: 'Bouclé · 40 × 40 cm',
    category: 'organisation',
    subcategories: [],
    spaces: ['living-room', 'bedroom'],
    styles: ['organic', 'warm-minimal'],
    collections: ['cosy-corner', 'small-spaces'],
    priceCents: 5990,
    materials: ['Polyester', 'Plywood'],
    colour: 'Cream',
    dimensions: '40 × 40 × 40 cm',
    weight: '3.8 kg',
    care: 'Brush the bouclé gently; spot clean spills.',
    shippingClass: 'STANDARD',
    imageKey: 'linen-cushions',
    copy: {
      intro: 'A soft bouclé pouf with a secret: sixty litres of storage under the lid.',
      benefits: ['Seat, footrest and storage in one', 'Lid sits flush for a clean silhouette', 'Light enough to move room to room'],
      use: 'Sofa corners, bedside and kids’ rooms.',
    },
    matchKeywords: ['storage ottoman', 'storage pouf'],
  },
];

export const KITCHEN_DINING: Archetype[] = [
  {
    key: 'acacia-serving-board',
    name: 'Acacia Serving Board',
    subtitle: '45 cm · juice groove · handle',
    category: 'kitchen-dining',
    subcategories: [],
    spaces: ['kitchen', 'dining'],
    styles: ['rustic-modern', 'natural', 'warm-minimal'],
    collections: ['modern-essentials', 'weekend-refresh'],
    priceCents: 3490,
    materials: ['Acacia'],
    colour: 'Brown',
    dimensions: '45 × 20 × 2 cm',
    weight: '1.2 kg',
    care: 'Hand wash; oil monthly with food-safe mineral oil.',
    shippingClass: 'SMALL',
    imageKey: 'serving-board',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    copy: {
      intro: 'One long acacia board for cheese nights, sourdough mornings and everything between.',
      benefits: ['Juice groove keeps counters clean', 'Leather loop hangs it as kitchen art', 'Dense acacia grain resists knife scars'],
      use: 'Serving, chopping and styling all in one.',
    },
    matchKeywords: ['serving board', 'cheese board', 'chopping board'],
  },
  {
    key: 'stoneware-dinner-set',
    name: 'Stoneware Dinner Set',
    subtitle: '4 settings · reactive glaze · 12 pieces',
    category: 'kitchen-dining',
    subcategories: [],
    spaces: ['kitchen', 'dining'],
    styles: ['organic', 'japandi', 'mediterranean'],
    collections: ['natural-objects', 'modern-essentials'],
    priceCents: 8990,
    materials: ['Ceramic'],
    colour: 'Sand',
    dimensions: 'Plates Ø 27/21 cm · bowls Ø 15 cm',
    weight: '6.5 kg',
    care: 'Dishwasher and microwave safe; avoid thermal shock.',
    shippingClass: 'FRAGILE',
    imageKey: 'dining-bowls',
    badge: "Editor's Pick",
    featured: true,
    copy: {
      intro: 'Twelve pieces of reactive-glazed stoneware where every plate carries its own soft tide-line.',
      benefits: ['Each glaze pools differently — no two alike', 'Chip-resistant stoneware for daily use', 'Plates stack slim in real cupboards'],
      use: 'Everyday dinners that deserve better plates.',
    },
    matchKeywords: ['stoneware dinner set', 'dinnerware set', 'ceramic plates set'],
  },
  {
    key: 'glass-storage-jars-set',
    name: 'Glass Storage Jars',
    subtitle: 'Set of 3 · bamboo lids · 1.2 L',
    category: 'kitchen-dining',
    subcategories: [],
    spaces: ['kitchen'],
    styles: ['scandinavian', 'modern', 'natural'],
    collections: ['modern-essentials', 'green-living'],
    priceCents: 2990,
    materials: ['Glass', 'Bamboo'],
    colour: 'Natural',
    dimensions: 'Ø 12 × 18 cm each',
    weight: '2.4 kg',
    care: 'Glass dishwasher safe; wipe bamboo lids by hand.',
    shippingClass: 'FRAGILE',
    imageKey: 'storage-jars',
    badge: 'Popular',
    copy: {
      intro: 'Pasta, oats and coffee in clear glass with bamboo lids — the pantry, quietly organised.',
      benefits: ['Airtight silicone seal keeps things crisp', 'Square bodies waste no shelf space', 'Reusable labels included'],
      use: 'Dry goods, grains and everything decanted.',
    },
    matchKeywords: ['storage jars', 'glass jars kitchen', 'pantry jars'],
  },
  {
    key: 'olive-wood-salad-set',
    name: 'Olive Wood Salad Servers',
    subtitle: 'Hand-carved · 30 cm pair',
    category: 'kitchen-dining',
    subcategories: [],
    spaces: ['kitchen', 'dining'],
    styles: ['organic', 'mediterranean', 'rustic-modern'],
    collections: ['mediterranean-garden', 'natural-objects'],
    priceCents: 2490,
    materials: ['Wood composite'],
    colour: 'Brown',
    dimensions: '30 cm pair',
    weight: '0.4 kg',
    care: 'Hand wash and dry; oil occasionally.',
    shippingClass: 'SMALL',
    imageKey: 'serving-board',
    copy: {
      intro: 'Hand-carved olive wood servers with the grain of a warm hillside.',
      benefits: ['Gentle on enamel and glass bowls', 'Each pair is one of a kind', 'Hangs from the kitchen rail nicely'],
      use: 'Salads, pasta and big Sunday bowls.',
    },
    matchKeywords: ['salad servers', 'olive wood utensils', 'wooden serving set'],
  },
  {
    key: 'linen-table-runner',
    name: 'Stonewashed Table Runner',
    subtitle: 'Belgian linen · 45 × 250 cm · oat',
    category: 'kitchen-dining',
    subcategories: [],
    spaces: ['dining'],
    styles: ['warm-minimal', 'natural', 'organic'],
    collections: ['soft-neutrals', 'cosy-corner'],
    priceCents: 2990,
    materials: ['Linen'],
    colour: 'Beige',
    dimensions: '45 × 250 cm',
    weight: '0.5 kg',
    care: 'Machine wash at 30°C; iron damp for a crisp finish.',
    shippingClass: 'SMALL',
    imageKey: 'linen-cushions',
    copy: {
      intro: 'A stonewashed linen runner that makes Tuesday dinner feel like a long table in Tuscany.',
      benefits: ['Softens with every wash', 'Generous 250 cm suits six seats', 'Neutral oat works all seasons'],
      use: 'Dining tables, sideboards and festive layers.',
    },
    matchKeywords: ['table runner linen', 'linen table runner'],
  },
];

export const GADGETS_SMART_HOME: Archetype[] = [
  {
    key: 'smart-plug-energy-pack',
    name: 'Smart Plug Energy Pack',
    subtitle: '4-pack · app + voice · schedules',
    category: 'gadgets-smart-home',
    subcategories: [],
    spaces: ['living-room', 'home-office', 'kitchen'],
    styles: ['modern', 'contemporary'],
    collections: ['modern-essentials'],
    priceCents: 3490,
    materials: ['Acrylic'],
    colour: 'White',
    dimensions: '5 × 5 × 7 cm each',
    weight: '0.3 kg pack',
    care: 'Indoor use; do not exceed 2,300 W per plug.',
    electrical: true,
    shippingClass: 'SMALL',
    imageKey: 'smart-lamp',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'Four smart plugs that give every lamp, fan and coffee machine a schedule and a voice.',
      benefits: ['Set-and-forget schedules from the app', 'Energy readouts per plug', 'Works with major voice assistants'],
      use: 'Lamps, heaters-on-timers and the radio by the bath.',
    },
    matchKeywords: ['smart plug', 'wifi plug', 'energy monitoring plug'],
  },
  {
    key: 'air-quality-monitor',
    name: 'Air Quality Monitor',
    subtitle: 'CO₂ · humidity · PM2.5 · e-ink',
    category: 'gadgets-smart-home',
    subcategories: [],
    spaces: ['bedroom', 'home-office'],
    styles: ['modern', 'minimal'],
    collections: ['modern-essentials', 'green-living'],
    priceCents: 7990,
    materials: ['Acrylic'],
    colour: 'White',
    dimensions: '9 × 9 × 4 cm',
    weight: '0.3 kg',
    care: 'Wipe with a dry cloth; recalibrate yearly per manual.',
    electrical: true,
    battery: true,
    shippingClass: 'SMALL',
    imageKey: 'smart-lamp',
    copy: {
      intro: 'A calm e-ink readout of the air you are actually breathing — CO₂, humidity and particles at a glance.',
      benefits: ['Alerts before the room gets stuffy', 'Weeks of battery per charge', 'History graphs in the app'],
      use: 'Bedrooms, nurseries and work-from-home desks.',
    },
    matchKeywords: ['air quality monitor', 'co2 monitor', 'air sensor'],
  },
  {
    key: 'aroma-diffuser-wood',
    name: 'Wood-Grain Aroma Diffuser',
    subtitle: '300 ml · 8 h mist · 7 light modes',
    category: 'gadgets-smart-home',
    subcategories: [],
    spaces: ['bedroom', 'living-room', 'bathroom'],
    styles: ['organic', 'japandi'],
    collections: ['japandi-calm', 'cosy-corner'],
    priceCents: 3990,
    materials: ['Acrylic', 'Wood composite'],
    colour: 'Brown',
    dimensions: 'Ø 13 × 20 cm',
    weight: '0.7 kg',
    care: 'Rinse the tank weekly; use water-based aromas only.',
    electrical: true,
    shippingClass: 'SMALL',
    imageKey: 'smart-lamp',
    badge: 'Popular',
    copy: {
      intro: 'A soft ultrasonic mist with a wood-grain shell — evening wind-down, automated.',
      benefits: ['Eight hours of whisper-quiet mist', 'Warm night-light with seven soft modes', 'Auto shut-off when the tank runs dry'],
      use: 'Bedside tables, baths and desks.',
    },
    matchKeywords: ['aroma diffuser', 'essential oil diffuser', 'ultrasonic diffuser'],
  },
  {
    key: 'video-doorbell-wirefree',
    name: 'Wire-Free Video Doorbell',
    subtitle: '2K HDR · person detection · chime',
    category: 'gadgets-smart-home',
    subcategories: [],
    spaces: ['entrance'],
    styles: ['modern', 'contemporary'],
    collections: ['modern-essentials'],
    priceCents: 11990,
    materials: ['Acrylic', 'Aluminium'],
    colour: 'Black',
    dimensions: '5 × 2.5 × 12 cm',
    weight: '0.3 kg',
    care: 'Charge the battery per app prompt; clean the lens gently.',
    electrical: true,
    battery: true,
    shippingClass: 'SMALL',
    imageKey: 'smart-lamp',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'A wire-free doorbell that tells a person from a parcel — and shows you both, in 2K.',
      benefits: ['Six months per battery charge', 'On-device person detection, fewer false alerts', 'Indoor chime and two-way talk included'],
      use: 'Front doors, apartment entries and side gates.',
    },
    matchKeywords: ['video doorbell', 'wireless doorbell camera', 'smart doorbell'],
  },
  {
    key: 'smart-light-strip-outdoor',
    name: 'Outdoor Smart Light Strip',
    subtitle: '5 m · IP65 · app scenes',
    category: 'gadgets-smart-home',
    subcategories: ['led-lighting'],
    spaces: ['balcony', 'terrace', 'garden'],
    styles: ['modern', 'contemporary'],
    collections: ['garden-glow', 'modern-essentials'],
    priceCents: 5990,
    materials: ['Polyester', 'Acrylic'],
    colour: 'Black',
    dimensions: '5 m strip',
    weight: '0.6 kg',
    care: 'Fix with the supplied clips; the controller stays dry indoors or in a box.',
    electrical: true,
    shippingClass: 'SMALL',
    imageKey: 'led-light-strip',
    badge: 'Featured',
    copy: {
      intro: 'An outdoor-rated smart strip that paints the balcony in movie-night colours — weather included in the design.',
      benefits: ['IP65 housing shrugs off rain', 'Millions of colours with warm-white scenes', 'Music sync for terrace evenings'],
      use: 'Balcony edges, pergola beams and gazebo lines.',
    },
    matchKeywords: ['outdoor led strip', 'smart outdoor lighting', 'ip65 light strip'],
  },
];

export const ACCESSORIES: Archetype[] = [
  {
    key: 'coir-doormat-natural',
    name: 'Natural Coir Doormat',
    subtitle: '80 × 50 cm · oak-look border',
    category: 'accessories',
    subcategories: [],
    spaces: ['entrance'],
    styles: ['natural', 'rustic-modern', 'warm-minimal'],
    collections: ['weekend-refresh', 'modern-essentials'],
    priceCents: 2490,
    materials: ['Jute'],
    colour: 'Natural',
    dimensions: '80 × 50 × 1.5 cm',
    weight: '1.7 kg',
    care: 'Shake out; keep dry; trim to fit if needed.',
    shippingClass: 'STANDARD',
    imageKey: 'doormat',
    badge: 'Popular',
    copy: {
      intro: 'A thick coir mat with a simple message: this home starts here.',
      benefits: ['Heavy bristles scrape boots properly', 'Non-slip backing grips tiles and stone', 'Natural fibre, low-key good looks'],
      use: 'Front doors, back doors and porch steps.',
    },
    matchKeywords: ['doormat', 'coir mat', 'entrance mat'],
  },
  {
    key: 'brass-plant-mister',
    name: 'Brass Plant Mister',
    subtitle: '300 ml · fine mist',
    category: 'accessories',
    subcategories: [],
    spaces: ['living-room', 'bathroom'],
    styles: ['modern', 'vintage', 'organic'],
    collections: ['green-living', 'natural-objects'],
    priceCents: 1990,
    materials: ['Metal'],
    colour: 'Brass',
    dimensions: 'H 18 cm · 300 ml',
    weight: '0.4 kg',
    care: 'Rinse between uses; polished brass softens with time.',
    shippingClass: 'SMALL',
    imageKey: 'decorative-tray',
    badge: 'Featured',
    featured: true,
    copy: {
      intro: 'A solid brass mister that turns plant care into a small, satisfying ritual.',
      benefits: ['Fine, even mist ferns actually enjoy', 'Pump action — no batteries, no plastic', 'Beautiful enough to live on the shelf'],
      use: 'Ferns, calatheas and orchid corners.',
    },
    matchKeywords: ['plant mister', 'brass spray bottle'],
  },
  {
    key: 'galvanised-watering-can',
    name: 'Galvanised Watering Can',
    subtitle: '1.7 L · long spout · steel',
    category: 'accessories',
    subcategories: [],
    spaces: ['garden', 'balcony'],
    styles: ['rustic-modern', 'modern', 'practical'],
    collections: ['green-living', 'weekend-refresh'],
    priceCents: 2990,
    materials: ['Steel'],
    colour: 'Silver',
    dimensions: '34 × 14 × 26 cm · 1.7 L',
    weight: '0.9 kg',
    care: 'Empty after use; a wipe of oil keeps the shine.',
    shippingClass: 'SMALL',
    imageKey: 'decorative-tray',
    copy: {
      intro: 'A classic galvanised can with a spout long enough to water the back row without wading in.',
      benefits: ['Balanced pour — gentle on seedlings', 'Removable rose for shower or stream', 'Galvanised steel for years of service'],
      use: 'Window boxes, balconies and greenhouse rows.',
    },
    matchKeywords: ['watering can', 'metal watering can', 'galvanised can'],
  },
  {
    key: 'wool-seat-pads-pair',
    name: 'Wool Seat Pads',
    subtitle: 'Set of 2 · 40 cm · mustard & grey',
    category: 'accessories',
    subcategories: [],
    spaces: ['dining', 'home-office'],
    styles: ['scandinavian', 'organic'],
    collections: ['cosy-corner', 'soft-neutrals'],
    priceCents: 2990,
    materials: ['Textile'],
    colour: 'Gold',
    dimensions: 'Ø 40 × 2 cm each',
    weight: '0.8 kg',
    care: 'Air regularly; sponge clean; keep away from moths.',
    shippingClass: 'SMALL',
    imageKey: 'linen-cushions',
    copy: {
      intro: 'Two thick wool pads that make hard chairs suddenly dinner-party friendly.',
      benefits: ['Real wool regulates temperature nicely', 'Ties hold them steady through dinner', 'Two-tone set suits mixed chairs'],
      use: 'Dining chairs, benches and window seats.',
    },
    matchKeywords: ['seat pads', 'chair cushions wool'],
  },
  {
    key: 'canvas-market-bag',
    name: 'Canvas Market Bag',
    subtitle: 'Organic cotton · long handles',
    category: 'accessories',
    subcategories: [],
    spaces: ['kitchen'],
    styles: ['natural', 'practical', 'organic'],
    collections: ['green-living', 'weekend-refresh'],
    priceCents: 1990,
    materials: ['Cotton'],
    colour: 'Natural',
    dimensions: '38 × 42 × 12 cm',
    weight: '0.3 kg',
    care: 'Machine wash at 30°C; air dry.',
    shippingClass: 'SMALL',
    imageKey: 'decorative-tray',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'A sturdy organic cotton tote for market mornings — bags that outlast the bananas.',
      benefits: ['Carries 15 kg without complaint', 'Wide base stands while you load', 'Washes back to bright'],
      use: 'Markets, libraries and the everyday haul.',
    },
    matchKeywords: ['market bag', 'canvas tote', 'cotton shopping bag'],
  },
];
