// ============================================================
// E-com.casa — Curated demo catalogue: LIGHTING (20)
// ------------------------------------------------------------
// 100% original E-com.casa copy and merchandising data.
// Structured as archetypes consumed by the product generator.
// ============================================================


import type { Archetype } from './types';

export const LIGHTING: Archetype[] = [
  {
    key: 'cordless-glow-portable-lamp',
    name: 'Cordless Glow Portable Lamp',
    subtitle: 'Cream · USB-C rechargeable · 3 warmth settings',
    category: 'lighting',
    subcategories: ['portable-lighting'],
    spaces: ['living-room', 'balcony', 'bedroom'],
    styles: ['warm-minimal', 'organic', 'modern'],
    collections: ['mood-lighting', 'cosy-corner', 'balcony-escape'],
    priceCents: 3990,
    materials: ['Steel', 'Polyester'],
    colour: 'Cream',
    dimensions: 'Ø 12 × 26 cm',
    weight: '0.9 kg',
    care: 'Wipe with a soft, dry cloth. Designed for covered outdoor use.',
    electrical: true,
    battery: true,
    shippingClass: 'SMALL',
    imageKey: 'led-table-lamp',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    variants: [
      { type: 'colour', name: 'Cream', value: 'cream' },
      { type: 'colour', name: 'Sage', value: 'sage' },
      { type: 'colour', name: 'Terracotta', value: 'terracotta' },
    ],
    copy: {
      intro: 'A soft, cordless glow you can carry from the dinner table to the balcony rail.',
      benefits: ['Three warmth settings with a soft-touch dimmer', 'Up to 30 hours of light per USB-C charge', 'Compact, lightweight and stable on any surface'],
      use: 'Made for slow dinners, late reading and evenings outdoors.',
    },
    matchKeywords: ['portable lamp', 'cordless', 'table lamp', 'rechargeable'],
  },
  {
    key: 'ceramic-glow-table-lamp',
    name: 'Ceramic Glow Table Lamp',
    subtitle: 'Warm cream glaze · linen shade',
    category: 'lighting',
    subcategories: ['portable-lighting'],
    spaces: ['bedroom', 'living-room'],
    styles: ['warm-minimal', 'natural'],
    collections: ['mood-lighting', 'soft-neutrals'],
    priceCents: 4490,
    materials: ['Ceramic', 'Linen'],
    colour: 'Cream',
    dimensions: 'Ø 20 × 32 cm',
    weight: '1.6 kg',
    care: 'Dust the shade with a dry cloth; clean the ceramic base with a damp cloth.',
    electrical: true,
    shippingClass: 'FRAGILE',
    imageKey: 'ceramic-table-lamp',
    featured: true,
    copy: {
      intro: 'A softly rounded ceramic base and natural linen shade that turn bedside light into a ritual.',
      benefits: ['Hand-glazed ceramic base with subtle variation', 'Linen shade diffuses a warm, even glow', 'In-line switch keeps the routine simple'],
      use: 'Sits beautifully on bedside tables, consoles and sideboards.',
    },
    matchKeywords: ['ceramic table lamp', 'bedside lamp'],
  },
  {
    key: 'willow-oak-floor-lamp',
    name: 'Willow Oak Floor Lamp',
    subtitle: 'Solid oak stem · paper shade',
    category: 'lighting',
    subcategories: ['portable-lighting'],
    spaces: ['living-room', 'bedroom', 'home-office'],
    styles: ['japandi', 'scandinavian', 'warm-minimal'],
    collections: ['warm-oak', 'cosy-corner'],
    priceCents: 12990,
    materials: ['Oak', 'Paper rope'],
    colour: 'Oak',
    dimensions: 'Ø 38 × 150 cm',
    weight: '4.2 kg',
    care: 'Dust the shade lightly; treat the oak with a dry cloth only.',
    electrical: true,
    shippingClass: 'OVERSIZED',
    imageKey: 'floor-lamp',
    badge: "Editor's Pick",
    isNew: true,
    copy: {
      intro: 'A quiet, architectural floor lamp in solid oak with a soft paper-rope shade.',
      benefits: ['Solid oak stem brings warmth and weight', 'Diffused, glare-free light for evening hours', 'Slim footprint fits reading corners and sofa sides'],
      use: 'Anchors reading corners and softens large, empty walls.',
    },
    matchKeywords: ['floor lamp', 'wooden floor lamp', 'reading light'],
  },
  {
    key: 'rattan-breeze-pendant',
    name: 'Rattan Breeze Pendant',
    subtitle: 'Woven rattan · Ø 45 cm',
    category: 'lighting',
    subcategories: ['led-lighting'],
    spaces: ['dining', 'living-room'],
    styles: ['natural', 'organic', 'mediterranean'],
    collections: ['natural-objects', 'statement-pieces'],
    priceCents: 7990,
    materials: ['Rattan'],
    colour: 'Natural',
    dimensions: 'Ø 45 × 32 cm · cable 150 cm',
    weight: '1.4 kg',
    care: 'Dust with a soft brush. Keep away from humid rooms.',
    electrical: true,
    shippingClass: 'STANDARD',
    imageKey: 'pendant-lamp',
    badge: 'Best Seller',
    isBestSeller: true,
    variants: [
      { type: 'size', name: 'Ø 45 cm', value: '45' },
      { type: 'size', name: 'Ø 55 cm', value: '55', deltaCents: 2000 },
    ],
    copy: {
      intro: 'Hand-woven rattan throws soft, patterned shadows across the room at dusk.',
      benefits: ['Open weave spreads a warm, textured light', 'Lightweight shade is easy to hang', 'Pairs with dimmable bulbs for full control'],
      use: 'Made for dining tables, breakfast nooks and hallway centres.',
    },
    matchKeywords: ['rattan pendant', 'woven pendant lamp', 'pendant shade'],
  },
  {
    key: 'halo-matte-pendant',
    name: 'Halo Matte Pendant',
    subtitle: 'Matte black · dome silhouette',
    category: 'lighting',
    subcategories: ['led-lighting'],
    spaces: ['dining', 'kitchen'],
    styles: ['modern', 'contemporary'],
    collections: ['modern-essentials', 'statement-pieces'],
    priceCents: 11990,
    materials: ['Aluminium'],
    colour: 'Black',
    dimensions: 'Ø 35 × 25 cm · cable 120 cm',
    weight: '1.8 kg',
    care: 'Wipe with a dry microfibre cloth to keep the matte finish even.',
    electrical: true,
    shippingClass: 'STANDARD',
    imageKey: 'pendant-lamp',
    copy: {
      intro: 'A clean domed pendant with a matte finish that draws the eye without shouting.',
      benefits: ['Direct, focused light over tables and islands', 'Adjustable cable length during installation', 'Timeless dome shape suits modern kitchens'],
      use: 'Hang in pairs over a dining table or in a row across a kitchen island.',
    },
    matchKeywords: ['black pendant lamp', 'metal pendant', 'dome pendant'],
  },
  {
    key: 'garden-string-lights',
    name: 'Garden String Lights',
    subtitle: 'Warm white · 10 m · solar',
    category: 'lighting',
    subcategories: ['outdoor-lighting'],
    spaces: ['garden', 'balcony', 'terrace'],
    styles: ['organic', 'mediterranean'],
    collections: ['garden-glow', 'balcony-escape'],
    priceCents: 3490,
    materials: ['Polyester', 'Steel'],
    colour: 'Black',
    dimensions: '10 m cable · 20 bulbs',
    care: 'Solar panel wipes clean with a damp cloth; store indoors in winter.',
    battery: true,
    shippingClass: 'SMALL',
    imageKey: 'string-lights',
    badge: 'Popular',
    isBestSeller: true,
    variants: [
      { type: 'size', name: '10 m', value: '10m' },
      { type: 'size', name: '20 m', value: '20m', deltaCents: 1500 },
    ],
    copy: {
      intro: 'A string of warm bulbs that turns any fence, pergola or balcony into an evening retreat.',
      benefits: ['Solar charging — no sockets needed', 'Warm-white bulbs with a gentle, steady glow', 'Flexible cable wraps railings, beams and hedges'],
      use: 'Drape above seating areas, along fences or across balcony railings.',
    },
    matchKeywords: ['string lights', 'solar string lights', 'garden fairy lights'],
  },
  {
    key: 'solar-cascade-lantern',
    name: 'Solar Cascade Lantern',
    subtitle: 'Solar charged · warm white LED',
    category: 'lighting',
    subcategories: ['outdoor-lighting'],
    spaces: ['garden', 'balcony', 'terrace'],
    styles: ['rustic-modern', 'natural'],
    collections: ['garden-glow', 'outdoor-living'],
    priceCents: 2990,
    materials: ['Metal', 'Glass'],
    colour: 'Black',
    dimensions: '12 × 12 × 18 cm',
    weight: '0.6 kg',
    care: 'Clean the solar panel regularly for the best charge.',
    battery: true,
    shippingClass: 'FRAGILE',
    imageKey: 'solar-lantern',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    variants: [
      { type: 'pack', name: 'Single', value: 'single' },
      { type: 'pack', name: 'Set of 2', value: 'set-2', deltaCents: 2200 },
      { type: 'pack', name: 'Set of 4', value: 'set-4', deltaCents: 5500 },
    ],
    copy: {
      intro: 'A classic lantern silhouette with a solar heart — set it out in the morning, enjoy it after dark.',
      benefits: ['Charges by day, glows automatically at dusk', 'Carry handle for tables, steps and pathways', 'Weather-friendly build for the season'],
      use: 'Line a garden path, cluster on a table, or hang from branches.',
    },
    matchKeywords: ['solar lantern', 'garden lantern', 'outdoor lantern'],
  },
  {
    key: 'ember-garden-torch',
    name: 'Ember Garden Torch',
    subtitle: 'Steel flame torch · 90 cm',
    category: 'lighting',
    subcategories: ['outdoor-lighting'],
    spaces: ['garden', 'terrace', 'patio'],
    styles: ['rustic-modern', 'modern'],
    collections: ['garden-glow', 'outdoor-living'],
    priceCents: 2490,
    materials: ['Steel'],
    colour: 'Black',
    dimensions: 'Ø 12 × 90 cm',
    weight: '1.1 kg',
    care: 'Store the wick indoors and clean the burner after use.',
    shippingClass: 'STANDARD',
    imageKey: 'garden-torch',
    copy: {
      intro: 'A slim steel torch that brings real flame warmth to summer evenings.',
      benefits: ['Stable ground spike for lawns and beds', 'Cylindrical guard keeps the flame steady', 'Instant atmosphere for outdoor dinners'],
      use: 'Place in groups along paths or around a terrace for a warm perimeter.',
    },
    matchKeywords: ['garden torch', 'flame torch', 'oil torch'],
  },
  {
    key: 'outdoor-wall-sconce-nox',
    name: 'Nox Outdoor Wall Light',
    subtitle: 'Matte black · IP44 rated',
    category: 'lighting',
    subcategories: ['outdoor-lighting'],
    spaces: ['entrance', 'terrace', 'patio'],
    styles: ['modern', 'contemporary'],
    collections: ['outdoor-living', 'modern-essentials'],
    priceCents: 5990,
    materials: ['Aluminium'],
    colour: 'Black',
    dimensions: '8 × 12 × 24 cm',
    weight: '1.2 kg',
    care: 'Wipe clean; check fixings seasonally.',
    electrical: true,
    shippingClass: 'STANDARD',
    imageKey: 'outdoor-wall-light',
    isNew: true,
    copy: {
      intro: 'A pared-back wall light that frames doors and terraces with a calm, downward glow.',
      benefits: ['Weather-resistant housing for year-round use', 'Warm downward beam — welcoming, never glaring', 'Low-profile silhouette suits rendered and brick walls'],
      use: 'Flank the front door, garage side or terrace steps.',
    },
    matchKeywords: ['outdoor wall light', 'exterior wall lamp', 'ip44 wall light'],
  },
  {
    key: 'bollard-path-light',
    name: 'Bollard Path Light',
    subtitle: 'Graphite · warm LED',
    category: 'lighting',
    subcategories: ['outdoor-lighting'],
    spaces: ['garden', 'entrance'],
    styles: ['modern', 'contemporary'],
    collections: ['outdoor-living'],
    priceCents: 8990,
    materials: ['Aluminium'],
    colour: 'Grey',
    dimensions: 'Ø 9 × 45 cm',
    weight: '1.5 kg',
    care: 'Wipe the diffuser clean; check fixings seasonally.',
    electrical: true,
    shippingClass: 'STANDARD',
    imageKey: 'outdoor-wall-light',
    copy: {
      intro: 'A low bollard that guides the way with a soft halo of light.',
      benefits: ['360° glow marks paths, beds and driveways', 'Sturdy body handles the seasons', 'Consistent warm temperature across a set'],
      use: 'Space along garden paths or around terrace edges.',
    },
    matchKeywords: ['bollard light', 'path light', 'garden bollard'],
  },
  {
    key: 'led-strip-warm-glow',
    name: 'Warm Glow LED Strip',
    subtitle: '2 m · self-adhesive · warm white',
    category: 'lighting',
    subcategories: ['led-lighting'],
    spaces: ['kitchen', 'living-room', 'home-office'],
    styles: ['modern', 'contemporary'],
    collections: ['modern-essentials', 'small-spaces'],
    priceCents: 1990,
    materials: ['Polyester', 'Aluminium'],
    colour: 'White',
    dimensions: '200 × 1 cm',
    care: 'Apply to clean, dry surfaces; do not bend sharply.',
    electrical: true,
    shippingClass: 'SMALL',
    imageKey: 'led-light-strip',
    badge: 'New',
    isNew: true,
    variants: [
      { type: 'size', name: '2 m', value: '2m' },
      { type: 'size', name: '5 m', value: '5m', deltaCents: 1000 },
    ],
    copy: {
      intro: 'A slim strip of warm light that lifts shelves, desks and cabinets out of the shadows.',
      benefits: ['Peel-and-stick backing for quick installs', 'Cuttable to length for a tidy finish', 'Low profile hides behind edges and trims'],
      use: 'Under kitchen cabinets, behind TVs or along shelf undersides.',
    },
    matchKeywords: ['led strip', 'light strip', 'led tape'],
  },
  {
    key: 'smart-ambient-light-bar',
    name: 'Smart Ambient Light Bar',
    subtitle: 'App + voice control · RGBW',
    category: 'lighting',
    subcategories: ['led-lighting'],
    spaces: ['living-room', 'home-office', 'bedroom'],
    styles: ['modern', 'contemporary'],
    collections: ['modern-essentials'],
    priceCents: 4990,
    materials: ['Aluminium', 'Acrylic'],
    colour: 'White',
    dimensions: '30 × 4 × 4 cm',
    weight: '0.5 kg',
    care: 'Wipe with a dry cloth; keep vents clear.',
    electrical: true,
    shippingClass: 'SMALL',
    imageKey: 'smart-lamp',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'An app-controlled light bar that shifts from focus white to cinema warmth in seconds.',
      benefits: ['Schedules and scenes from your phone', 'Syncs with music and screen content', 'Sits flat or mounts behind monitors and TVs'],
      use: 'Behind desks, TVs and headboards for layered, controllable light.',
    },
    matchKeywords: ['smart light bar', 'rgb light', 'app controlled light'],
  },
  {
    key: 'dawn-reading-light',
    name: 'Dawn Rechargeable Reading Light',
    subtitle: 'Sage green · clip-on · USB-C',
    category: 'lighting',
    subcategories: ['portable-lighting'],
    spaces: ['bedroom', 'home-office'],
    styles: ['modern', 'warm-minimal'],
    collections: ['mood-lighting', 'small-spaces'],
    priceCents: 2490,
    materials: ['Aluminium'],
    colour: 'Green',
    dimensions: '10 × 8 × 30 cm',
    weight: '0.4 kg',
    care: 'Charge fully before first use; wipe with a dry cloth.',
    electrical: true,
    battery: true,
    shippingClass: 'SMALL',
    imageKey: 'led-table-lamp',
    copy: {
      intro: 'A featherlight reading light that clamps to headboards and shelves and goes for weeks.',
      benefits: ['Flexible neck aims light exactly where needed', 'Three brightness levels, including soft night mode', 'Clip base spares your surfaces'],
      use: 'Clip to a headboard, desk shelf or balcony rail.',
    },
    matchKeywords: ['clip light', 'reading lamp', 'rechargeable reading light'],
  },
  {
    key: 'luna-linen-table-lamp',
    name: 'Luna Linen Table Lamp',
    subtitle: 'Sand linen · oak base',
    category: 'lighting',
    subcategories: ['portable-lighting'],
    spaces: ['living-room', 'bedroom'],
    styles: ['warm-minimal', 'scandinavian'],
    collections: ['soft-neutrals', 'cosy-corner'],
    priceCents: 5490,
    materials: ['Linen', 'Oak'],
    colour: 'Sand',
    dimensions: 'Ø 24 × 40 cm',
    weight: '1.3 kg',
    care: 'Vacuum the shade on low; dust the base with a dry cloth.',
    electrical: true,
    shippingClass: 'STANDARD',
    imageKey: 'ceramic-table-lamp',
    copy: {
      intro: 'Soft sand-toned linen over a turned oak base — an easy, calming presence on any surface.',
      benefits: ['Natural linen shade gives a gentle, even glow', 'Solid oak base adds quiet warmth', 'Standard fitting for easy bulb swaps'],
      use: 'On sideboards, chests of drawers and bedside tables.',
    },
    matchKeywords: ['linen table lamp', 'oak lamp', 'bedside table lamp'],
  },
  {
    key: 'dome-brass-pendant',
    name: 'Dome Brass Pendant',
    subtitle: 'Brushed brass · Ø 30 cm',
    category: 'lighting',
    subcategories: ['led-lighting'],
    spaces: ['dining', 'entrance'],
    styles: ['neo-deco', 'modern'],
    collections: ['statement-pieces', 'modern-essentials'],
    priceCents: 14990,
    materials: ['Brass'],
    colour: 'Brass',
    dimensions: 'Ø 30 × 22 cm · cable 100 cm',
    weight: '1.9 kg',
    care: 'Buff gently with a soft cloth to maintain the brushed finish.',
    electrical: true,
    shippingClass: 'STANDARD',
    imageKey: 'pendant-lamp',
    badge: "Editor's Pick",
    copy: {
      intro: 'A brushed brass dome that brings a warm, jewellery-like glow to the table.',
      benefits: ['Interior reflects light for a rich, warm pool', 'Adjustable cable for high and low ceilings', 'Pairs with dimmers for full evening control'],
      use: 'Hang solo over an entrance table or in pairs over dining.',
    },
    matchKeywords: ['brass pendant', 'gold pendant lamp'],
  },
  {
    key: 'solar-path-stakes',
    name: 'Solar Path Stakes',
    subtitle: 'Set of 6 · warm white',
    category: 'lighting',
    subcategories: ['outdoor-lighting'],
    spaces: ['garden', 'entrance'],
    styles: ['modern', 'natural'],
    collections: ['garden-glow', 'weekend-refresh'],
    priceCents: 2290,
    materials: ['Steel'],
    colour: 'Black',
    dimensions: 'Ø 5 × 35 cm each',
    weight: '0.3 kg each',
    care: 'Keep panels clear of leaves and snow.',
    battery: true,
    shippingClass: 'SMALL',
    imageKey: 'garden-torch',
    variants: [{ type: 'pack', name: 'Set of 6', value: 'set-6' }],
    copy: {
      intro: 'Six solar stakes that trace a gentle line of light along paths and borders.',
      benefits: ['Push-in stakes — no wiring at all', 'Auto on at dusk, off at dawn', 'Warm white tone is soft on evening gardens'],
      use: 'Line driveways, beds and the edge of the lawn.',
    },
    matchKeywords: ['solar path lights', 'garden stakes solar', 'solar stake lights'],
  },
  {
    key: 'festoon-bulb-set',
    name: 'Festoon Bulb Set',
    subtitle: '15 m · 25 shatter-safe bulbs',
    category: 'lighting',
    subcategories: ['outdoor-lighting'],
    spaces: ['garden', 'terrace', 'patio'],
    styles: ['rustic-modern', 'mediterranean'],
    collections: ['garden-glow', 'outdoor-living'],
    priceCents: 6990,
    materials: ['Steel', 'Glass'],
    colour: 'Black',
    dimensions: '15 m cable',
    weight: '1.6 kg',
    care: 'Hang with slack to avoid tension on the cable; store dry in winter.',
    electrical: true,
    shippingClass: 'STANDARD',
    imageKey: 'string-lights',
    badge: 'Popular',
    variants: [
      { type: 'size', name: '15 m', value: '15m' },
      { type: 'size', name: '25 m', value: '25m', deltaCents: 2500 },
    ],
    copy: {
      intro: 'The classic festoon: a generous run of glowing bulbs that makes any evening feel like a courtyard in June.',
      benefits: ['Long 15 m run covers pergolas and courtyards', 'Shatter-safe bulbs for family gardens', 'Connectable end-to-end for longer runs'],
      use: 'Span a pergola, terrace or garden seating area.',
    },
    matchKeywords: ['festoon lights', 'outdoor string bulbs', 'patio lights'],
  },
  {
    key: 'glow-orb-solar',
    name: 'Glow Orb Solar Light',
    subtitle: 'Frosted orb · ground stake or table',
    category: 'lighting',
    subcategories: ['outdoor-lighting'],
    spaces: ['garden', 'balcony'],
    styles: ['organic', 'modern'],
    collections: ['garden-glow', 'balcony-escape'],
    priceCents: 3590,
    materials: ['Acrylic', 'Steel'],
    colour: 'White',
    dimensions: 'Ø 16 cm',
    weight: '0.5 kg',
    care: 'Wipe the dome to keep the glow bright.',
    battery: true,
    shippingClass: 'SMALL',
    imageKey: 'solar-lantern',
    isNew: true,
    copy: {
      intro: 'A softly frosted orb that floats light over beds, borders and balcony boxes.',
      benefits: ['Two modes: table stand or ground stake', 'Charges by day — no cables, no fuss', 'Warm, diffuse glow flatters plants at night'],
      use: 'Cluster in borders, or place on outdoor tables and window sills.',
    },
    matchKeywords: ['solar orb light', 'solar globe', 'solar ball light'],
  },
  {
    key: 'wall-washer-uplight',
    name: 'Wall Washer Uplight',
    subtitle: 'Slate grey · adjustable head',
    category: 'lighting',
    subcategories: ['led-lighting'],
    spaces: ['living-room', 'entrance'],
    styles: ['modern', 'contemporary'],
    collections: ['statement-pieces', 'wall-makeover'],
    priceCents: 4590,
    materials: ['Aluminium'],
    colour: 'Grey',
    dimensions: '10 × 9 × 14 cm',
    weight: '0.8 kg',
    care: 'Wipe with a dry cloth; aim the head before fixing permanently.',
    electrical: true,
    shippingClass: 'SMALL',
    imageKey: 'floor-lamp',
    copy: {
      intro: 'A discreet uplight that turns plants, art and textured walls into evening features.',
      benefits: ['Adjustable head for precise aiming', 'Compact body hides behind plants and furniture', 'Warm beam adds depth to slatted and textured walls'],
      use: 'At the base of feature walls, plants and alcoves.',
    },
    matchKeywords: ['uplight', 'wall washer light', 'accent light'],
  },
  {
    key: 'cloud-night-light',
    name: 'Cloud Night Light',
    subtitle: 'Soft silicone · tap dimmer',
    category: 'lighting',
    subcategories: ['portable-lighting'],
    spaces: ['bedroom'],
    styles: ['organic', 'modern'],
    collections: ['cosy-corner', 'small-spaces'],
    priceCents: 1890,
    materials: ['Silicone', 'Acrylic'],
    colour: 'White',
    dimensions: 'Ø 11 × 8 cm',
    weight: '0.3 kg',
    care: 'Wipe with a damp cloth; charge via the supplied cable.',
    electrical: true,
    battery: true,
    shippingClass: 'SMALL',
    imageKey: 'smart-lamp',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'A pocket of calm light for late-night reading and gentle goodnights.',
      benefits: ['Tap anywhere to dim or switch off', 'Warm, low-glare mode protects sleepy eyes', 'Soft-touch silicone is safe to handle'],
      use: 'On bedside tables, shelves and window ledges.',
    },
    matchKeywords: ['night light', 'kids night lamp', 'touch lamp'],
  },
];
