// ============================================================
// E-com.casa — Curated demo catalogue:
//   WALL PANELS (15) + INTERIOR DECORATION (18)
// 100% original E-com.casa copy and merchandising data.
// ============================================================

import type { Archetype } from './types';

export const WALL_PANELS: Archetype[] = [
  {
    key: 'warm-oak-slat-panel',
    name: 'Warm Oak Slatted Wall Panel',
    subtitle: 'Natural oak · 240 × 60 cm',
    category: 'wall-panels',
    subcategories: ['wood-slat-panels'],
    spaces: ['living-room', 'bedroom', 'home-office'],
    styles: ['warm-minimal', 'japandi', 'natural'],
    collections: ['wall-makeover', 'warm-oak'],
    priceCents: 4990,
    materials: ['Oak', 'Polyester'],
    colour: 'Oak',
    dimensions: '240 × 60 cm · 2.2 cm slat depth',
    weight: '7.5 kg',
    care: 'Wipe with a dry microfibre cloth; avoid direct water exposure.',
    shippingClass: 'OVERSIZED',
    imageKey: 'wood-slat-panel',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    variants: [
      { type: 'colour', name: 'Natural Oak', value: 'oak' },
      { type: 'colour', name: 'Walnut', value: 'walnut', deltaCents: 1000 },
      { type: 'colour', name: 'Black', value: 'black', deltaCents: 500 },
    ],
    copy: {
      intro: 'Precision-milled oak slats on a soft acoustic backing that give flat walls rhythm, depth and calm.',
      benefits: ['Cuts easily to size for clean, built-in results', 'Felt backing softens echoes in bright rooms', 'Panels butt together for a continuous slat line'],
      use: 'Feature walls behind sofas, beds and desks.',
    },
    matchKeywords: ['slat wall panel', 'wood slat panel', 'acoustic panel'],
  },
  {
    key: 'walnut-slat-panel-wide',
    name: 'Wide Slat Wall Panel Walnut',
    subtitle: 'Walnut finish · 240 × 60 cm · wide slat',
    category: 'wall-panels',
    subcategories: ['wood-slat-panels'],
    spaces: ['living-room', 'dining'],
    styles: ['modern', 'japandi'],
    collections: ['wall-makeover', 'statement-pieces'],
    priceCents: 5990,
    materials: ['Wood composite', 'Polyester'],
    colour: 'Walnut',
    dimensions: '240 × 60 cm · 4 cm slat width',
    weight: '8.2 kg',
    care: 'Dust along the slats with a dry cloth or soft brush.',
    shippingClass: 'OVERSIZED',
    imageKey: 'wood-slat-panel',
    isNew: true,
    badge: 'New',
    variants: [
      { type: 'colour', name: 'Walnut', value: 'walnut' },
      { type: 'colour', name: 'Natural Oak', value: 'oak' },
    ],
    copy: {
      intro: 'A wider slat profile for bolder lines — the same calm acoustic comfort with a more architectural stance.',
      benefits: ['Wide slats read cleanly across large walls', 'Acoustic backing softens open-plan noise', 'Walnut finish pairs with brass and linen'],
      use: 'Statement walls in living rooms and dining spaces.',
    },
    matchKeywords: ['wide slat panel', 'walnut wall panel'],
  },
  {
    key: 'black-slat-panel',
    name: 'Noir Slatted Wall Panel',
    subtitle: 'Matte black · 240 × 60 cm',
    category: 'wall-panels',
    subcategories: ['wood-slat-panels'],
    spaces: ['living-room', 'home-office'],
    styles: ['modern', 'contemporary'],
    collections: ['wall-makeover', 'statement-pieces'],
    priceCents: 5290,
    materials: ['Wood composite', 'Polyester'],
    colour: 'Black',
    dimensions: '240 × 60 cm · 2.2 cm slat depth',
    weight: '7.8 kg',
    care: 'Wipe with a dry microfibre cloth.',
    shippingClass: 'OVERSIZED',
    imageKey: 'wood-slat-panel',
    copy: {
      intro: 'Deep, matte black slats that turn media walls and desks into sharp, focused backdrops.',
      benefits: ['High contrast makes screens and art pop', 'Acoustic backing absorbs office chatter', 'Matte finish resists fingerprints and sheen'],
      use: 'TV walls, gaming corners and dark-accent interiors.',
    },
    matchKeywords: ['black slat panel', 'black acoustic panel'],
  },
  {
    key: 'slat-panel-sample-trio',
    name: 'Slat Panel Sample Trio',
    subtitle: 'Oak · Walnut · Black finishes',
    category: 'wall-panels',
    subcategories: ['wood-slat-panels'],
    spaces: ['home-office'],
    styles: ['modern'],
    collections: ['wall-makeover'],
    priceCents: 990,
    materials: ['Wood composite'],
    colour: 'Natural',
    dimensions: '10 × 20 cm × 3',
    weight: '0.3 kg',
    care: 'Keep dry; samples are for finish reference.',
    shippingClass: 'SMALL',
    imageKey: 'wood-slat-panel',
    badge: 'Popular',
    copy: {
      intro: 'Three finishes, one decision made easy — feel the grain and colour before you commit.',
      benefits: ['True-to-product finishes in hand', 'Ideal for checking colour against floors and sofas', 'Refundable against a full panel order'],
      use: 'Compare finishes at home in your own light.',
    },
    matchKeywords: ['slat panel sample', 'panel sample'],
  },
  {
    key: 'felt-acoustic-tiles',
    name: 'Felt Acoustic Wall Tiles',
    subtitle: 'Set of 12 · sage green',
    category: 'wall-panels',
    subcategories: ['decorative-panels'],
    spaces: ['home-office', 'bedroom'],
    styles: ['modern', 'scandinavian'],
    collections: ['wall-makeover', 'small-spaces'],
    priceCents: 3990,
    materials: ['Polyester'],
    colour: 'Green',
    dimensions: '30 × 30 cm each',
    weight: '2.4 kg',
    care: 'Vacuum on low with a brush head; spot clean with a damp cloth.',
    shippingClass: 'STANDARD',
    imageKey: 'wood-slat-panel',
    variants: [
      { type: 'colour', name: 'Sage', value: 'sage' },
      { type: 'colour', name: 'Sand', value: 'sand' },
      { type: 'colour', name: 'Charcoal', value: 'charcoal' },
    ],
    copy: {
      intro: 'Soft geometric tiles that quiet a room while giving you a colour to play with.',
      benefits: ['Noticeably calmer echoes in hard rooms', 'Mix colours into patterns and gradients', 'Lightweight — mount with the included strips'],
      use: 'Desks, music corners, kids’ rooms and rentals.',
    },
    matchKeywords: ['acoustic tiles', 'felt wall tiles', 'sound panels'],
  },
  {
    key: 'fluted-wall-panel',
    name: 'Fluted Wood Wall Panel',
    subtitle: 'White oak veneer · 120 × 60 cm',
    category: 'wall-panels',
    subcategories: ['decorative-panels'],
    spaces: ['entrance', 'living-room'],
    styles: ['japandi', 'warm-minimal'],
    collections: ['wall-makeover', 'soft-neutrals'],
    priceCents: 4590,
    materials: ['Oak', 'Plywood'],
    colour: 'Oak',
    dimensions: '120 × 60 cm · 1.5 cm flute depth',
    weight: '5.6 kg',
    care: 'Dust with a dry cloth along the flutes.',
    shippingClass: 'OVERSIZED',
    imageKey: 'wood-slat-panel',
    copy: {
      intro: 'Fine vertical flutes with a calm, tailored rhythm — panelling without the joinery.',
      benefits: ['Continuous fluted look across joined panels', 'Real wood veneer, sealed for daily life', 'Lighter visual weight than open slats'],
      use: 'Hallways, behind beds and built-in style joinery walls.',
    },
    matchKeywords: ['fluted panel', 'fluted wood panel', 'wall panelling'],
  },
  {
    key: 'stone-effect-panel',
    name: 'Stone-Effect Wall Panel',
    subtitle: 'Soft grey ledger · 120 × 30 cm',
    category: 'wall-panels',
    subcategories: ['decorative-panels'],
    spaces: ['living-room', 'kitchen'],
    styles: ['rustic-modern', 'modern'],
    collections: ['wall-makeover'],
    priceCents: 3990,
    materials: ['PVC', 'Wood composite'],
    colour: 'Grey',
    dimensions: '120 × 30 cm × 4 panels',
    weight: '9.0 kg',
    care: 'Wipe with a damp cloth; avoid abrasive cleaners.',
    shippingClass: 'HEAVY',
    imageKey: 'wood-slat-panel',
    copy: {
      intro: 'Ledger-stone texture in a light, clip-together panel — the feature wall without the masonry.',
      benefits: ['Stone texture at a fraction of the weight', 'Interlocking edges keep joints invisible', 'Suitable around fireplaces (check clearances)'],
      use: 'Chimney breasts, media walls and kitchen splashback features.',
    },
    matchKeywords: ['stone wall panel', 'ledger panel', 'stone effect cladding'],
  },
  {
    key: 'wpc-outdoor-wall-cladding',
    name: 'Outdoor Slat Cladding Panel',
    subtitle: 'WPC · weather-resistant · 290 × 16 cm',
    category: 'wall-panels',
    subcategories: ['wood-slat-panels'],
    spaces: ['garden', 'terrace', 'balcony'],
    styles: ['modern', 'natural'],
    collections: ['outdoor-living', 'wall-makeover'],
    priceCents: 6990,
    materials: ['WPC'],
    colour: 'Oak',
    dimensions: '290 × 16 cm',
    weight: '6.8 kg',
    care: 'Rinse occasionally with water and a soft brush.',
    shippingClass: 'HEAVY',
    imageKey: 'wood-slat-panel',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'Weather-proof slat cladding that brings the warm slatted look to balconies and garden rooms.',
      benefits: ['Composite slats shrug off rain and sun', 'No staining or painting, year after year', 'Fixes to walls, fences and planters'],
      use: 'Balcony walls, garden rooms, and tired fencing.',
    },
    matchKeywords: ['outdoor wall cladding', 'wpc slat panel', 'garden wall panel'],
  },
  {
    key: 'arch-panel-headboard',
    name: 'Arched Panel Headboard',
    subtitle: 'Upholstered · bouclé cream · 140 cm',
    category: 'wall-panels',
    subcategories: ['decorative-panels'],
    spaces: ['bedroom'],
    styles: ['warm-minimal', 'organic'],
    collections: ['cosy-corner', 'soft-neutrals'],
    priceCents: 14990,
    materials: ['Polyester', 'Plywood'],
    colour: 'Cream',
    dimensions: '140 × 110 × 6 cm',
    weight: '12 kg',
    care: 'Brush gently; blot spills immediately.',
    shippingClass: 'OVERSIZED',
    imageKey: 'wood-slat-panel',
    badge: "Editor's Pick",
    copy: {
      intro: 'A softly arched, bouclé-wrapped panel that turns any bed into the calm centre of the room.',
      benefits: ['Wall-mounted design floats above the floor', 'Textured bouclé adds gentle depth', 'Fits standard double beds — no drill into the bed frame'],
      use: 'Above beds, or as a softening panel in reading corners.',
    },
    matchKeywords: ['upholstered headboard', 'wall headboard', 'boucle headboard'],
  },
  {
    key: 'oak-peg-rail-panel',
    name: 'Oak Peg Rail Panel',
    subtitle: 'Solid oak · 5 pegs · 80 cm',
    category: 'wall-panels',
    subcategories: ['decorative-panels'],
    spaces: ['entrance', 'home-office'],
    styles: ['scandinavian', 'natural'],
    collections: ['warm-oak', 'small-spaces'],
    priceCents: 3490,
    materials: ['Oak'],
    colour: 'Oak',
    dimensions: '80 × 8 × 7 cm',
    weight: '1.5 kg',
    care: 'Wipe with a dry cloth; re-tighten screws seasonally.',
    shippingClass: 'SMALL',
    imageKey: 'oak-wall-shelf',
    badge: 'Popular',
    copy: {
      intro: 'A simple Shaker-style rail in solid oak — coats, bags and hats, handled beautifully.',
      benefits: ['Turned pegs hold loops without snags', 'Solid oak ages with character', 'Two-screw mounting into studs or plugs'],
      use: 'Entrances, kitchens and home offices.',
    },
    matchKeywords: ['peg rail', 'shaker rail', 'coat rail oak'],
  },
  {
    key: 'herringbone-panel',
    name: 'Herringbone Accent Panel',
    subtitle: 'Smoked oak veneer · 120 × 60 cm',
    category: 'wall-panels',
    subcategories: ['decorative-panels'],
    spaces: ['living-room', 'dining'],
    styles: ['rustic-modern', 'neo-deco'],
    collections: ['wall-makeover', 'statement-pieces'],
    priceCents: 5490,
    materials: ['Oak', 'Plywood'],
    colour: 'Brown',
    dimensions: '120 × 60 cm',
    weight: '6.4 kg',
    care: 'Dust with a dry cloth; avoid polishing the veneer.',
    shippingClass: 'OVERSIZED',
    imageKey: 'wood-slat-panel',
    copy: {
      intro: 'Smoked oak laid in a herringbone pattern — quiet drama for feature walls and alcoves.',
      benefits: ['Pre-assembled pattern keeps the geometry perfect', 'Smoked tone adds depth to light rooms', 'Butts neatly against slat panels for contrast'],
      use: 'Alcove backs, fireplace surrounds and hallways.',
    },
    matchKeywords: ['herringbone panel', 'herringbone wall'],
  },
  {
    key: 'kids-slat-panel-soft',
    name: 'Soft Slat Panel Pastel',
    subtitle: 'Blush felt backing · 120 × 60 cm',
    category: 'wall-panels',
    subcategories: ['wood-slat-panels'],
    spaces: ['bedroom'],
    styles: ['organic', 'scandinavian'],
    collections: ['small-spaces', 'weekend-refresh'],
    priceCents: 4290,
    materials: ['Wood composite', 'Polyester'],
    colour: 'Cream',
    dimensions: '120 × 60 cm',
    weight: '4.9 kg',
    care: 'Vacuum the felt on low; dust slats with a dry cloth.',
    shippingClass: 'OVERSIZED',
    imageKey: 'wood-slat-panel',
    isNew: true,
    variants: [
      { type: 'colour', name: 'Blush', value: 'blush' },
      { type: 'colour', name: 'Sky', value: 'sky' },
    ],
    copy: {
      intro: 'A shorter slat panel with soft pastel backing, sized for nurseries and small bedrooms.',
      benefits: ['Gentle palette designed for restful rooms', 'Felt backing softens playtime noise', 'Shorter panel is light enough for one person'],
      use: 'Above cots and beds, or as a reading-nook backdrop.',
    },
    matchKeywords: ['slat panel small', 'pastel wall panel'],
  },
  {
    key: 'bamboo-panel-natural',
    name: 'Bamboo Slat Wall Panel',
    subtitle: 'Natural bamboo · 180 × 60 cm',
    category: 'wall-panels',
    subcategories: ['wood-slat-panels'],
    spaces: ['living-room', 'bathroom'],
    styles: ['japandi', 'organic', 'natural'],
    collections: ['japandi-calm', 'natural-objects'],
    priceCents: 4790,
    materials: ['Bamboo'],
    colour: 'Natural',
    dimensions: '180 × 60 cm',
    weight: '5.2 kg',
    care: 'Dust with a dry cloth; keep clear of direct shower steam.',
    shippingClass: 'OVERSIZED',
    imageKey: 'wood-slat-panel',
    copy: {
      intro: 'Slim bamboo slats with a calm, even grain — a lighter, faster-growing take on the slat wall.',
      benefits: ['Bamboo brings fine texture to small rooms', 'Sealed finish handles everyday humidity', 'Warm neutral tone suits most palettes'],
      use: 'Bedrooms, studios and calm corners.',
    },
    matchKeywords: ['bamboo wall panel', 'bamboo slat'],
  },
  {
    key: 'mirror-panel-arch-set',
    name: 'Arched Mirror Wall Set',
    subtitle: 'Set of 2 · brass rim · 45 & 60 cm',
    category: 'wall-panels',
    subcategories: ['decorative-panels'],
    spaces: ['entrance', 'living-room'],
    styles: ['neo-deco', 'mediterranean'],
    collections: ['statement-pieces', 'soft-neutrals'],
    priceCents: 8990,
    materials: ['Glass', 'Metal'],
    colour: 'Brass',
    dimensions: '45 × 90 cm & 35 × 70 cm',
    weight: '6.0 kg',
    care: 'Clean glass with standard glass cleaner; frame with a dry cloth.',
    shippingClass: 'FRAGILE',
    imageKey: 'arched-mirror',
    badge: 'Featured',
    featured: true,
    copy: {
      intro: 'Two arches of light — hung together they open a wall, a hallway, a whole corner of the day.',
      benefits: ['Mixed heights create an easy gallery rhythm', 'Slim brass rims keep the look light', 'Arched glass doubles daylight in darker rooms'],
      use: 'Entrance walls, above sideboards and console tables.',
    },
    matchKeywords: ['arched mirror set', 'wall mirror set', 'arch mirror'],
  },
  {
    key: 'cane-webbing-panel',
    name: 'Cane Webbing Screen Panel',
    subtitle: 'Natural cane · oak frame · 90 × 120 cm',
    category: 'wall-panels',
    subcategories: ['decorative-panels'],
    spaces: ['living-room', 'home-office', 'balcony'],
    styles: ['organic', 'mediterranean', 'natural'],
    collections: ['natural-objects', 'small-spaces'],
    priceCents: 6490,
    materials: ['Bamboo', 'Oak'],
    colour: 'Natural',
    dimensions: '90 × 120 × 2 cm',
    weight: '3.4 kg',
    care: 'Dust with a soft brush; keep away from prolonged moisture.',
    shippingClass: 'STANDARD',
    imageKey: 'wood-slat-panel',
    isNew: true,
    copy: {
      intro: 'Woven cane in an oak frame — a room divider and feature panel that lets light wander through.',
      benefits: ['Divides rooms without closing them off', 'Warm woven texture softens hard interiors', 'Hangs flat or stands in a bracket'],
      use: 'Home offices, studio corners and rental-friendly makeovers.',
    },
    matchKeywords: ['cane webbing panel', 'cane screen', 'room divider panel'],
  },
];

export const DECORATION: Archetype[] = [
  {
    key: 'arched-wall-mirror',
    name: 'Arched Wall Mirror',
    subtitle: 'Brass frame · 60 × 90 cm',
    category: 'decoration',
    subcategories: ['mirrors'],
    spaces: ['living-room', 'bedroom', 'bathroom'],
    styles: ['neo-deco', 'modern', 'warm-minimal'],
    collections: ['soft-neutrals', 'statement-pieces'],
    priceCents: 7990,
    materials: ['Metal', 'Glass'],
    colour: 'Brass',
    dimensions: '60 × 90 × 2.5 cm',
    weight: '5.5 kg',
    care: 'Clean glass with standard glass cleaner; frame with a dry cloth.',
    shippingClass: 'FRAGILE',
    imageKey: 'arched-mirror',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    copy: {
      intro: 'A quietly arched silhouette in a slim brass frame that lifts light and height out of any wall.',
      benefits: ['Soft arch flatters hallways and bedrooms', 'Hangs vertical or leans against the wall', 'Float glass gives a clear, true reflection'],
      use: 'Above consoles, behind sofas and in entrances.',
    },
    matchKeywords: ['arched mirror', 'wall mirror', 'brass mirror'],
  },
  {
    key: 'full-length-leaning-mirror',
    name: 'Full-Length Leaning Mirror',
    subtitle: 'Thin black frame · 70 × 170 cm',
    category: 'decoration',
    subcategories: ['mirrors'],
    spaces: ['bedroom', 'entrance'],
    styles: ['modern', 'contemporary'],
    collections: ['statement-pieces'],
    priceCents: 12990,
    materials: ['Glass', 'Aluminium'],
    colour: 'Black',
    dimensions: '70 × 170 × 2 cm',
    weight: '11 kg',
    care: 'Clean with glass cleaner; check the lean angle on carpet.',
    shippingClass: 'FRAGILE',
    imageKey: 'arched-mirror',
    copy: {
      intro: 'A full-length mirror with a whisper-thin frame — designed to lean, not shout.',
      benefits: ['Head-to-toe reflection in a slim profile', 'Anti-slip pads keep the lean safe', 'Oversized glass brightens dark corners'],
      use: 'Bedrooms, dress corners and hallways.',
    },
    matchKeywords: ['full length mirror', 'leaning mirror', 'floor mirror'],
  },
  {
    key: 'ceramic-vase-trio',
    name: 'Sculpted Ceramic Vase Trio',
    subtitle: 'Matte stoneware · set of 3',
    category: 'decoration',
    subcategories: [],
    spaces: ['living-room', 'dining'],
    styles: ['organic', 'japandi', 'natural'],
    collections: ['natural-objects', 'soft-neutrals'],
    priceCents: 4990,
    materials: ['Ceramic'],
    colour: 'Cream',
    dimensions: 'H 18 / 24 / 30 cm',
    weight: '2.9 kg',
    care: 'Rinse with warm water; avoid dishwasher and harsh detergents.',
    shippingClass: 'FRAGILE',
    imageKey: 'ceramic-vase-set',
    badge: 'Best Seller',
    isBestSeller: true,
    featured: true,
    copy: {
      intro: 'Three rounded stoneware vases in stepping heights — a still life that works even without flowers.',
      benefits: ['Grouped silhouettes styled in one box', 'Matte glaze pairs with dried and fresh stems', 'Weighted bases keep tall stems steady'],
      use: 'Console tables, shelves and dining centrepieces.',
    },
    matchKeywords: ['ceramic vase set', 'stoneware vase', 'vase trio'],
  },
  {
    key: 'terracotta-table-vase',
    name: 'Terracotta Table Vase',
    subtitle: 'Unglazed terracotta · H 22 cm',
    category: 'decoration',
    subcategories: [],
    spaces: ['dining', 'living-room'],
    styles: ['mediterranean', 'rustic-modern'],
    collections: ['mediterranean-garden', 'natural-objects'],
    priceCents: 2490,
    materials: ['Ceramic'],
    colour: 'Terracotta',
    dimensions: 'Ø 14 × 22 cm',
    weight: '1.4 kg',
    care: 'Wipe with a dry cloth; a water-filled liner is recommended for fresh stems.',
    shippingClass: 'FRAGILE',
    imageKey: 'ceramic-vase-set',
    copy: {
      intro: 'Warm, unglazed terracotta with the soft matteness of a summer courtyard.',
      benefits: ['Natural clay tone warms neutral palettes', 'Narrow neck supports loose, airy stems', 'Sits beautifully with olive greens and linen'],
      use: 'Dining tables, kitchen windows and shelf styling.',
    },
    matchKeywords: ['terracotta vase', 'clay vase'],
  },
  {
    key: 'framed-print-pair',
    name: 'Earth-Tone Print Pair',
    subtitle: '2 framed prints · oak · A3',
    category: 'decoration',
    subcategories: [],
    spaces: ['living-room', 'home-office'],
    styles: ['warm-minimal', 'japandi'],
    collections: ['soft-neutrals', 'weekend-refresh'],
    priceCents: 5990,
    materials: ['Wood composite', 'Glass'],
    colour: 'Sand',
    dimensions: 'A3 each · 30 × 42 cm',
    weight: '1.8 kg',
    care: 'Dust frames with a dry cloth; avoid direct sunlight.',
    shippingClass: 'FRAGILE',
    imageKey: 'wall-art',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'A pair of gallery-weight frames with exclusive E-com.casa earth-tone artwork — calm geometry for bare walls.',
      benefits: ['Arrives framed, glazed and ready to hang', 'Exclusive prints you won’t see everywhere', 'Oak-look frames suit warm and neutral rooms'],
      use: 'Above sofas, sideboards and desks.',
    },
    matchKeywords: ['framed print', 'wall art set', 'poster pair'],
  },
  {
    key: 'wall-clock-natural',
    name: 'Natural Wood Wall Clock',
    subtitle: 'Oak veneer · silent movement · Ø 30 cm',
    category: 'decoration',
    subcategories: [],
    spaces: ['kitchen', 'home-office', 'living-room'],
    styles: ['scandinavian', 'warm-minimal'],
    collections: ['modern-essentials', 'warm-oak'],
    priceCents: 3990,
    materials: ['Oak', 'Metal'],
    colour: 'Oak',
    dimensions: 'Ø 30 × 4 cm',
    weight: '1.1 kg',
    care: 'Dust with a dry cloth; one AA battery (not included).',
    shippingClass: 'SMALL',
    imageKey: 'wall-clock',
    badge: 'Popular',
    copy: {
      intro: 'A clean, quiet clock in warm oak veneer — the time, told softly.',
      benefits: ['Silent sweep movement — no ticking', 'Slim oak ring suits kitchens and studies', 'Bold numerals read across the room'],
      use: 'Kitchens, hallways and work-from-home walls.',
    },
    matchKeywords: ['wooden wall clock', 'silent wall clock', 'oak clock'],
  },
  {
    key: 'linen-cushion-set',
    name: 'Linen Cushion Set',
    subtitle: 'Set of 2 · oatmeal & olive',
    category: 'decoration',
    subcategories: [],
    spaces: ['living-room', 'bedroom'],
    styles: ['natural', 'warm-minimal', 'organic'],
    collections: ['cosy-corner', 'soft-neutrals'],
    priceCents: 3990,
    materials: ['Linen', 'Polyester'],
    colour: 'Sand',
    dimensions: '45 × 45 cm each',
    weight: '1.2 kg',
    care: 'Cover machine washable at 30°C; air dry.',
    shippingClass: 'SMALL',
    imageKey: 'linen-cushions',
    badge: 'Best Seller',
    isBestSeller: true,
    variants: [
      { type: 'colour', name: 'Oatmeal & Olive', value: 'oat-olive' },
      { type: 'colour', name: 'Rust & Cream', value: 'rust-cream' },
      { type: 'colour', name: 'Grey & Sand', value: 'grey-sand' },
    ],
    copy: {
      intro: 'Stonewashed linen covers in two tonal shades — the fastest way to make a sofa look lived-in.',
      benefits: ['Breathable linen softens with every wash', 'Hidden zips keep the look clean', 'Plump inserts included and filled just right'],
      use: 'Sofas, reading chairs and bed corners.',
    },
    matchKeywords: ['linen cushions', 'cushion set', 'throw pillows'],
  },
  {
    key: 'chunky-knit-throw',
    name: 'Chunky Knit Throw',
    subtitle: 'Recycled cotton · honey beige · 130 × 170 cm',
    category: 'decoration',
    subcategories: [],
    spaces: ['living-room', 'bedroom'],
    styles: ['organic', 'scandinavian'],
    collections: ['cosy-corner', 'weekend-refresh'],
    priceCents: 5990,
    materials: ['Cotton'],
    colour: 'Beige',
    dimensions: '130 × 170 cm',
    weight: '1.8 kg',
    care: 'Gentle machine wash at 30°C; dry flat to keep the stitch.',
    shippingClass: 'STANDARD',
    imageKey: 'linen-cushions',
    badge: 'Featured',
    featured: true,
    copy: {
      intro: 'A generous, heavyweight knit made from recycled cotton — the sofa’s favourite winter companion.',
      benefits: ['Chunky stitch traps warmth without weight', 'Recycled cotton yarn, softer each wash', 'Large enough to share on movie nights'],
      use: 'Over sofa arms, bed ends and reading chairs.',
    },
    matchKeywords: ['knit throw', 'chunky blanket', 'sofa throw'],
  },
  {
    key: 'oak-floating-shelf-duo',
    name: 'Oak Floating Shelf Duo',
    subtitle: 'Solid oak · 60 cm · set of 2',
    category: 'decoration',
    subcategories: [],
    spaces: ['living-room', 'bathroom', 'home-office'],
    styles: ['scandinavian', 'japandi', 'natural'],
    collections: ['warm-oak', 'small-spaces'],
    priceCents: 4490,
    materials: ['Oak'],
    colour: 'Oak',
    dimensions: '60 × 14 × 4 cm each',
    weight: '2.6 kg',
    care: 'Wipe with a dry cloth; hold up to 8 kg when properly fixed.',
    shippingClass: 'SMALL',
    imageKey: 'oak-wall-shelf',
    badge: 'Popular',
    copy: {
      intro: 'Two solid oak shelves with invisible fixings — books, plants and small objects, floating.',
      benefits: ['Hidden brackets for a clean line', 'Solid oak carries real weight', 'Two lengths stack into a simple wall scheme'],
      use: 'Above desks, bedsides and bathroom alcoves.',
    },
    matchKeywords: ['floating shelf oak', 'wooden wall shelf'],
  },
  {
    key: 'ceramic-candle-trio',
    name: 'Ceramic Candle Trio',
    subtitle: 'Sage · sand · clay · unscented',
    category: 'decoration',
    subcategories: [],
    spaces: ['living-room', 'dining'],
    styles: ['organic', 'mediterranean'],
    collections: ['cosy-corner', 'mediterranean-garden'],
    priceCents: 2990,
    materials: ['Ceramic'],
    colour: 'Green',
    dimensions: 'Ø 8 × 9 / 11 / 13 cm',
    weight: '1.5 kg',
    care: 'Trim wicks to 5 mm before each burn; never leave burning candles unattended.',
    shippingClass: 'FRAGILE',
    imageKey: 'candle-set',
    isNew: true,
    badge: 'New',
    copy: {
      intro: 'Three ceramic candle holders in earthy glazes — instant table warmth, matches or no matches.',
      benefits: ['Stepped heights style a table in seconds', 'Fits standard dinner and pillar candles', 'Glazed inside for easy wax clean-up'],
      use: 'Dining tables, mantels and bath ledges.',
    },
    matchKeywords: ['candle holders set', 'ceramic candle', 'candle trio'],
  },
  {
    key: 'decorative-oak-tray',
    name: 'Oak Styling Tray',
    subtitle: 'Solid oak · raised edge · 40 cm',
    category: 'decoration',
    subcategories: [],
    spaces: ['living-room', 'kitchen'],
    styles: ['scandinavian', 'warm-minimal'],
    collections: ['warm-oak', 'modern-essentials'],
    priceCents: 3490,
    materials: ['Oak'],
    colour: 'Oak',
    dimensions: '40 × 28 × 4 cm',
    weight: '1.1 kg',
    care: 'Wipe with a dry cloth; occasional food-safe oil keeps the grain fed.',
    shippingClass: 'SMALL',
    imageKey: 'decorative-tray',
    copy: {
      intro: 'One tray that corrals the everyday — keys and candles by day, coffee and pastries on Sunday.',
      benefits: ['Raised edges keep everything in place', 'Solid oak with a softly rounded rim', 'Doubles as a serving tray for guests'],
      use: 'Coffee tables, consoles and kitchen counters.',
    },
    matchKeywords: ['oak tray', 'decorative tray', 'serving tray wood'],
  },
  {
    key: 'sculptural-bookends',
    name: 'Sculptural Bookends',
    subtitle: 'Powder-coated steel · set of 2',
    category: 'decoration',
    subcategories: [],
    spaces: ['home-office', 'living-room'],
    styles: ['modern', 'contemporary'],
    collections: ['modern-essentials', 'home-office'],
    priceCents: 2990,
    materials: ['Steel'],
    colour: 'Black',
    dimensions: '12 × 10 × 12 cm each',
    weight: '1.6 kg',
    care: 'Wipe with a dry cloth; felt pads protect shelves.',
    shippingClass: 'SMALL',
    imageKey: 'decorative-tray',
    copy: {
      intro: 'Quiet, weighty arcs that hold a shelf of books like they were placed by a set designer.',
      benefits: ['Heavy steel base holds serious book rows', 'Felt underside protects timber shelves', 'Sculptural enough to style alone'],
      use: 'Shelves, desks and sideboards.',
    },
    matchKeywords: ['bookends', 'metal bookends'],
  },
  {
    key: 'dried-grass-bouquet',
    name: 'Dried Grass Bouquet',
    subtitle: 'Natural pampas & bunny tails · H 70 cm',
    category: 'decoration',
    subcategories: [],
    spaces: ['living-room', 'bedroom'],
    styles: ['organic', 'boho', 'natural'],
    collections: ['natural-objects', 'soft-neutrals'],
    priceCents: 1990,
    materials: ['Textile'],
    colour: 'Natural',
    dimensions: 'H 70 cm · 15 stems',
    weight: '0.3 kg',
    care: 'Shake gently to fluff; keep out of direct sunlight to slow fading.',
    shippingClass: 'SMALL',
    imageKey: 'ceramic-vase-set',
    badge: 'New',
    isNew: true,
    copy: {
      intro: 'A soft, cloud-like bouquet of dried grasses — zero maintenance, all-season texture.',
      benefits: ['Lasts years with no water or light needs', 'Feathered plumes fill tall vases fast', 'Warm natural tone suits any palette'],
      use: 'Floor vases, bedroom corners and entry consoles.',
    },
    matchKeywords: ['dried pampas', 'dried flowers', 'dried grass'],
  },
  {
    key: 'photo-frame-set-oak',
    name: 'Oak Photo Frame Set',
    subtitle: 'Set of 3 · A4, A5, 10×15',
    category: 'decoration',
    subcategories: [],
    spaces: ['entrance', 'bedroom', 'living-room'],
    styles: ['scandinavian', 'warm-minimal'],
    collections: ['warm-oak', 'weekend-refresh'],
    priceCents: 2990,
    materials: ['Oak', 'Glass'],
    colour: 'Oak',
    dimensions: 'A4 + A5 + 10 × 15 cm',
    weight: '1.0 kg',
    care: 'Wipe with a dry cloth; glass cleans with standard cleaner.',
    shippingClass: 'SMALL',
    imageKey: 'oak-wall-shelf',
    copy: {
      intro: 'Three slim oak frames in gallery proportions — a shelf, a ledge or a wall, sorted.',
      benefits: ['Matching set takes the guesswork out of styling', 'Both hanging and standing fixings included', 'Real glass fronts, not film'],
      use: 'Console styling, shelves and bedside vignettes.',
    },
    matchKeywords: ['photo frame set', 'oak frames'],
  },
  {
    key: 'incense-holder-set',
    name: 'Stone Incense Holder Set',
    subtitle: 'Sandstone holder + 30 sticks',
    category: 'decoration',
    subcategories: [],
    spaces: ['living-room', 'bathroom'],
    styles: ['japandi', 'organic'],
    collections: ['japandi-calm', 'cosy-corner'],
    priceCents: 1990,
    materials: ['Stone'],
    colour: 'Sand',
    dimensions: '12 × 5 × 3 cm',
    weight: '0.5 kg',
    care: 'Wipe clean; burn in ventilated rooms on heat-safe surfaces.',
    shippingClass: 'SMALL',
    imageKey: 'candle-set',
    copy: {
      intro: 'A solid sandstone dish and a month of calm — slow evenings in three gentle scents.',
      benefits: ['Heavy stone catches every ash flake', 'Three scent families: cedar, fig, neroli', 'Compact enough for bathroom shelves'],
      use: 'Desks, baths and anywhere five quiet minutes happen.',
    },
    matchKeywords: ['incense holder', 'incense set'],
  },
  {
    key: 'entry-console-styling-set',
    name: 'Entryway Styling Set',
    subtitle: 'Tray + bowl + frame · oak & ceramic',
    category: 'decoration',
    subcategories: [],
    spaces: ['entrance'],
    styles: ['warm-minimal', 'modern'],
    collections: ['weekend-refresh', 'modern-essentials'],
    priceCents: 4990,
    materials: ['Oak', 'Ceramic'],
    colour: 'Natural',
    dimensions: 'Tray 35 cm · bowl Ø 12 cm · A5 frame',
    weight: '1.9 kg',
    care: 'Wipe timber dry; ceramic washes by hand.',
    shippingClass: 'STANDARD',
    imageKey: 'decorative-tray',
    badge: "Editor's Pick",
    copy: {
      intro: 'Everything a good entrance needs: a drop-zone tray, a key bowl and one perfect frame.',
      benefits: ['Curated set — no styling guesswork', 'Solid oak and glazed ceramic, made to last', 'Works on any console or shelf depth'],
      use: 'Hallway tables, entrance shelves and apartment entries.',
    },
    matchKeywords: ['entryway decor set', 'console styling'],
  },
  {
    key: 'round-wall-mirror-rope',
    name: 'Rope Rim Round Mirror',
    subtitle: 'Natural rope frame · Ø 70 cm',
    category: 'decoration',
    subcategories: ['mirrors'],
    spaces: ['bathroom', 'bedroom', 'entrance'],
    styles: ['mediterranean', 'organic', 'coastal'],
    collections: ['mediterranean-garden', 'natural-objects'],
    priceCents: 6990,
    materials: ['Glass', 'Jute'],
    colour: 'Natural',
    dimensions: 'Ø 70 × 3 cm',
    weight: '2.8 kg',
    care: 'Dust the rope with a soft brush; glass with standard cleaner.',
    shippingClass: 'FRAGILE',
    imageKey: 'arched-mirror',
    variants: [
      { type: 'size', name: 'Ø 70 cm', value: '70' },
      { type: 'size', name: 'Ø 90 cm', value: '90', deltaCents: 2500 },
    ],
    copy: {
      intro: 'A circle of light with a hand-wrapped rope rim — coastal warmth for bathrooms and bedrooms.',
      benefits: ['Round shape softens tiled and angular rooms', 'Chunky rope rim adds beach-house texture', 'Light enough for plasterboard walls'],
      use: 'Above vanities, dressers and entrance hooks.',
    },
    matchKeywords: ['round rope mirror', 'boho mirror', 'round wall mirror'],
  },
  {
    key: 'stacked-books-decor',
    name: 'Decorative Book Stack',
    subtitle: 'Set of 3 · linen spines',
    category: 'decoration',
    subcategories: [],
    spaces: ['living-room', 'home-office'],
    styles: ['japandi', 'warm-minimal'],
    collections: ['japandi-calm', 'soft-neutrals'],
    priceCents: 2490,
    materials: ['Paper', 'Linen'],
    colour: 'Cream',
    dimensions: '24 × 17 × 8 cm stacked',
    weight: '1.3 kg',
    care: 'Keep dry; dust spines with a soft brush.',
    shippingClass: 'SMALL',
    imageKey: 'decorative-tray',
    copy: {
      intro: 'Linen-wrapped design books that give a shelf instant depth — styled height, no effort.',
      benefits: ['Neutral spines match any scheme', 'Real books with beautiful inside pages', 'Perfect riser for small objects'],
      use: 'Coffee tables, shelves and console layers.',
    },
    matchKeywords: ['decorative books', 'coffee table books'],
  },
];
