// ============================================================
// E-com.casa — Normalizer
// ------------------------------------------------------------
// Normalizes prices, currencies, dimensions, weights, colours,
// materials and names. Original source values are preserved in
// raw research records; normalization output feeds scoring and
// product generation only.
// ============================================================

export interface NormalizedCandidate {
  sourceKey: string;
  sourceUrl: string;
  sourceProductId?: string;
  sourceProductName: string;
  sourceBrand?: string;
  sourceDescription?: string;
  sourcePrice?: number;
  sourceSalePrice?: number;
  sourceCurrency: string;
  sourceAvailability?: string;
  sourceSku?: string;
  sourceGtin?: string;
  sourceMaterials?: string;
  sourceColours?: string;
  sourceDimensions?: string;
  sourceWeight?: string;
  sourceImageUrls: string[];
  sourceAttributes: Record<string, string>;
  normalized: {
    nameClean: string;
    priceEur?: number;
    currencyOriginal: string;
    materialsList: string[];
    coloursList: string[];
    dims?: { length?: number; width?: number; height?: number; depth?: number; diameter?: number; unit: string };
    weightKg?: number;
    categoryHint?: string;
    isElectricalHint: boolean;
    isBatteryHint: boolean;
  };
  extractionMethod: string;
}

const CURRENCY_SYMBOLS: Record<string, string> = {
  '€': 'EUR',
  '£': 'GBP',
  '$': 'USD',
};

/** FX reference rates for market-intelligence normalisation ONLY.
 *  Demo prices are generated by E-com.casa pricing logic — these are
 *  never presented as supplier costs. */
export const FX_TO_EUR: Record<string, number> = {
  EUR: 1,
  GBP: 1.17,
  USD: 0.92,
  DKK: 0.134,
  SEK: 0.087,
  PLN: 0.23,
  CZK: 0.04,
  HUF: 0.0025,
  RON: 0.2,
  BGN: 0.51,
};

export function parsePrice(raw?: string, currencyHint?: string): { value?: number; currency: string } {
  if (!raw) return { currency: currencyHint ?? 'EUR' };
  let currency = currencyHint ?? 'EUR';
  for (const [sym, code] of Object.entries(CURRENCY_SYMBOLS)) {
    if (raw.includes(sym)) currency = code;
  }
  const num = raw.replace(/[^\d.,]/g, '');
  if (!num) return { currency };
  // Handle "1.299,00" (EU) vs "1,299.00" (UK/US)
  let normalized: number;
  const lastComma = num.lastIndexOf(',');
  const lastDot = num.lastIndexOf('.');
  if (lastComma > lastDot) normalized = parseFloat(num.replace(/\./g, '').replace(',', '.'));
  else normalized = parseFloat(num.replace(/,/g, ''));
  if (!Number.isFinite(normalized) || normalized <= 0 || normalized > 100_000) return { currency };
  return { value: normalized, currency };
}

export function toEur(value: number, currency: string): number | undefined {
  const rate = FX_TO_EUR[currency];
  return rate ? Math.round(value * rate * 100) / 100 : undefined;
}

const COLOUR_MAP: Array<[RegExp, string]> = [
  [/natural\s?oak|light\s?oak|eiche natural/i, 'Oak'],
  [/walnut|nogal|noyer/i, 'Walnut'],
  [/matte black|black finish|black|schwarz|noir|nero/i, 'Black'],
  [/off.?white|creamy|cream|creme/i, 'Cream'],
  [/beige|sand|taupe/i, 'Sand'],
  [/grey|gray|grau|gris/i, 'Grey'],
  [/olive/i, 'Olive'],
  [/sage|green|vert|grun|verde/i, 'Green'],
  [/terracotta|terracota/i, 'Terracotta'],
  [/brass|messing|laiton/i, 'Brass'],
  [/gold|doré|gold finish/i, 'Gold'],
  [/silver|silber|argent/i, 'Silver'],
  [/white|weiß|blanc|bianco/i, 'White'],
  [/brown|braun|marron|marrone/i, 'Brown'],
  [/blue|blau|bleu|blu/i, 'Blue'],
];

const MATERIAL_MAP: Array<[RegExp, string]> = [
  [/solid oak|oak veneer|\boak\b|eiche|chene|roble/i, 'Oak'],
  [/walnut|nogal|noyer/i, 'Walnut'],
  [/plywood/i, 'Plywood'],
  [/wood composite|MDF|fibreboard/i, 'Wood composite'],
  [/powder.?coated steel|\bsteel\b|acier|stahl|acero/i, 'Steel'],
  [/aluminium|aluminum|aluminio/i, 'Aluminium'],
  [/\bmetal\b|metall|metal/i, 'Metal'],
  [/ceramic|ceramica|keramik/i, 'Ceramic'],
  [/stoneware|stone-effect|stone effect|\bstone\b/i, 'Stone'],
  [/fibre stone|fiberstone|fibrestone/i, 'Fibre stone'],
  [/tempered glass|\bglass\b|glas|verre|vidrio/i, 'Glass'],
  [/rattan|rotan|roten/i, 'Rattan'],
  [/bamboo|bambu|bambous/i, 'Bamboo'],
  [/teak|tecka/i, 'Teak'],
  [/acacia/i, 'Acacia'],
  [/linen|lino|leinen/i, 'Linen'],
  [/cotton|algodon|baumwolle|coton/i, 'Cotton'],
  [/polyester/i, 'Polyester'],
  [/\bwpc\b/i, 'WPC'],
  [/\bpvc\b/i, 'PVC'],
  [/jute|sisal/i, 'Jute'],
  [/seagrass|sea grass/i, 'Seagrass'],
  [/marble|marmol|marbre|marmor/i, 'Marble'],
  [/concrete|beton/i, 'Concrete'],
  [/paper rope|paper cord/i, 'Paper rope'],
];

export function normalizeColours(text?: string): string[] {
  if (!text) return [];
  const found = new Set<string>();
  for (const [re, norm] of COLOUR_MAP) {
    if (re.test(text)) found.add(norm);
    if (found.size >= 3) break;
  }
  return [...found];
}

export function normalizeMaterials(text?: string): string[] {
  if (!text) return [];
  const found = new Set<string>();
  for (const [re, norm] of MATERIAL_MAP) {
    if (re.test(text)) found.add(norm);
    if (found.size >= 4) break;
  }
  return [...found];
}

const DIM_RE =
  /(\d{1,4}(?:[.,]\d{1,2})?)\s?(?:x|×|\*|by)\s?(\d{1,4}(?:[.,]\d{1,2})?)(?:\s?(?:x|×|\*|by)\s?(\d{1,4}(?:[.,]\d{1,2})?))?\s?(mm|cm|m|")?/i;

export function normalizeDimensions(text?: string): NormalizedCandidate['normalized']['dims'] | undefined {
  if (!text) return undefined;
  const m = text.match(DIM_RE);
  if (!m) return undefined;
  const unit = (m[4] ?? 'cm').toLowerCase();
  const toCm = (v: string) => {
    let n = parseFloat(v.replace(',', '.'));
    if (!Number.isFinite(n)) return undefined;
    if (unit === 'mm') n = n / 10;
    if (unit === 'm') n = n * 100;
    if (unit === '"') n = n * 2.54;
    return Math.round(n * 10) / 10;
  };
  const l = toCm(m[1]);
  const w = toCm(m[2]);
  const h = m[3] ? toCm(m[3]) : undefined;
  if (l === undefined || w === undefined) return undefined;
  return { length: l, width: w, height: h, unit: 'cm' };
}

export function normalizeWeight(text?: string): number | undefined {
  if (!text) return undefined;
  const kg = text.match(/(\d{1,3}(?:[.,]\d{1,2})?)\s?kg/i);
  if (kg) return parseFloat(kg[1].replace(',', '.'));
  const g = text.match(/(\d{1,5})\s?g\b/i);
  if (g) return Math.round((parseInt(g[1], 10) / 1000) * 100) / 100;
  return undefined;
}

const ELECTRICAL_RE = /lamp|light|led|luminaire|pendant|chandelier|spot|smart (light|plug|bulb)|electrical|plug.?in|rechargeable|usb/i;
const BATTERY_RE = /battery|solar|rechargeable|cordless|wireless|akku|batterie/i;

export interface NormalizeInput {
    sourceKey: string;
    sourceUrl: string;
    sourceProductId?: string;
    sourceProductName?: string;
    sourceBrand?: string;
    sourceDescription?: string;
    price?: string;
    currency?: string;
    availability?: string;
    sku?: string;
    gtin?: string;
    materials?: string;
    colours?: string;
    dimensions?: string;
    weight?: string;
    imageUrls?: string[];
    attributes?: Record<string, string>;
    extractionMethod: string;
    currencyHint?: string;
    categoryHint?: string;
  }

export function normalizeCandidate(
  candidate: {
    sourceKey: string;
    sourceUrl: string;
    sourceProductId?: string;
    sourceProductName?: string;
    sourceBrand?: string;
    sourceDescription?: string;
    price?: string;
    currency?: string;
    availability?: string;
    sku?: string;
    gtin?: string;
    materials?: string;
    colours?: string;
    dimensions?: string;
    weight?: string;
    imageUrls?: string[];
    attributes?: Record<string, string>;
    extractionMethod: string;
    currencyHint?: string;
    categoryHint?: string;
  },
): NormalizedCandidate | null {
  const name = (candidate.sourceProductName ?? '').trim();
  if (name.length < 3 || name.length > 220) return null;
  // Reject obviously non-product pages
  if (/checkout|cart|account|login|privacy|terms|cookie|robots\.txt|sitemap/i.test(candidate.sourceUrl)) return null;

  const { value: price, currency } = parsePrice(candidate.price, candidate.currencyHint ?? candidate.currency);
  const priceEur = price !== undefined ? toEur(price, currency) : undefined;
  const text = `${name} ${candidate.sourceDescription ?? ''} ${candidate.materials ?? ''}`;
  const dims = normalizeDimensions(candidate.dimensions ?? candidate.sourceDescription);

  return {
    sourceKey: candidate.sourceKey,
    sourceUrl: candidate.sourceUrl,
    sourceProductId: candidate.sourceProductId,
    sourceProductName: name,
    sourceBrand: candidate.sourceBrand,
    sourceDescription: candidate.sourceDescription?.slice(0, 800),
    sourcePrice: price,
    sourceSalePrice: undefined,
    sourceCurrency: currency,
    sourceAvailability: candidate.availability,
    sourceSku: candidate.sku,
    sourceGtin: candidate.gtin,
    sourceMaterials: candidate.materials,
    sourceColours: candidate.colours,
    sourceDimensions: candidate.dimensions,
    sourceWeight: candidate.weight,
    sourceImageUrls: (candidate.imageUrls ?? []).slice(0, 6),
    sourceAttributes: candidate.attributes ?? {},
    normalized: {
      nameClean: name
        .replace(/\s+/g, ' ')
        .replace(/[|–—].*$/, '')
        .trim()
        .slice(0, 120),
      priceEur,
      currencyOriginal: currency,
      materialsList: normalizeMaterials(`${candidate.materials ?? ''} ${candidate.sourceDescription ?? ''}`),
      coloursList: normalizeColours(candidate.colours ?? name),
      dims,
      weightKg: normalizeWeight(candidate.weight),
      categoryHint: candidate.categoryHint,
      isElectricalHint: ELECTRICAL_RE.test(text),
      isBatteryHint: BATTERY_RE.test(text),
    },
    extractionMethod: candidate.extractionMethod,
  };
}

/** Fingerprint for dedupe — normalized name + category + key attributes. */
export function fingerprint(n: NormalizedCandidate): string {
  const key = [n.normalized.nameClean.toLowerCase().replace(/[^a-z0-9]+/g, '-'), Math.round(n.normalized.priceEur ?? 0)]
    .join('|');
  return key;
}
